.gitignore
We shouldn't include build files (*.app) in the repo as they change with every build and add unnecessary files to the repo. 
The launch.json files are specific to environment and also not needed in repo.
=> adding *.app and **/launch.json files to .gitignore

Modules/DevTools/TestFramework/Any/app/app.json, Modules/DevTools/TestFramework/Any/app/src/Any.Codeunit.al, Modules/DevTools/TestFramework/Assert/app/app.json, Modules/DevTools/TestFramework/Assert/app/src/LibraryAssert.Codeunit.al, Modules/DevTools/TestTools/TestRunner/app/app.json, Modules/DevTools/TestTools/TestRunner/app/src/ALTestSuite.Table.al, Modules/DevTools/TestTools/TestRunner/app/src/ALTestSuites.Page.al, Modules/DevTools/TestTools/TestRunner/app/src/ALTestTool.Page.al, Modules/DevTools/TestTools/TestRunner/app/src/CommandLineTestTool.Page.al, Modules/DevTools/TestTools/TestRunner/app/src/SelectTestRunner.Page.al, Modules/DevTools/TestTools/TestRunner/app/src/SelectTests.Page.al, Modules/DevTools/TestTools/TestRunner/app/src/SelectTestsByRange.Page.al, Modules/DevTools/TestTools/TestRunner/app/src/TestMethodLine.Table.al, Modules/DevTools/TestTools/TestRunner/app/src/TestProfileManagement.Codeunit.al, Modules/DevTools/TestTools/TestRunner/app/src/TestRoleCenter.Page.al, Modules/DevTools/TestTools/TestRunner/app/src/TestRunnerGetMethods.Codeunit.al, Modules/DevTools/TestTools/TestRunner/app/src/TestRunnerIsolCodeunit.Codeunit.al, Modules/DevTools/TestTools/TestRunner/app/src/TestRunnerIsolDisabled.Codeunit.al, Modules/DevTools/TestTools/TestRunner/app/src/TestRunnerMgt.Codeunit.al, Modules/DevTools/TestTools/TestRunner/app/src/TestRunnerProgessDialog.Codeunit.al, Modules/DevTools/TestTools/TestRunner/app/src/TestSuiteMgt.Codeunit.al, Modules/System/Satisfaction Survey/src/SatisfactionSurveyAsync.ControlAddIn.al, Modules/System/js/SATAsync.js
From developer: The js file need to be duplicated in the modules root because of the problem with a relative path to js files in controladdins (bug logged). It is a workaround to be able to compile both the big system application module and SAT module.
=> Control add in workaround

BREAKINGCHANGES.md
Inform users why they should not be using the old GetPlatformVersion function anymore.
=> Update breaking change

Modules/System/Assisted Setup/src/AssistedSetup.Codeunit.al, Modules/System/Assisted Setup/src/AssistedSetupImpl.Codeunit.al
Discussed this feature in Yammer with Soumya Dutta:
https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=314088954175488&search_origin=global&scoring=linear1Y-prankie-group-private-higher&match=any-exact&search_sort=relevance&page=1&search=assisted%20setup.
We need this function in test scenarios to make sure that the wizard's complete status is reseted before opening the assisted setup.
If the assisted setup is not reseted a confirm will appear. But if its not completed, the confirm will not appear.
Because there is no "optional confirmhandler" the reset function is the easiest way to solve this behavior.
=> Added Reset function to the assisted setup

BREAKINGCHANGES.md
If someone use the GetLanguageId function in v15 e.g. to switch language on report, there is possibility to get error
`Invalid language ID: 0`
if empty code is passed. This is common on e.g. reports for printing Sales Invoice.
Using GetLanguageIdOrDefault is the correct solution.
=> Update BREAKINGCHANGES.md GetLanguageId part

AddOns/Elster/app/src/Reports/REP11016.CreateXMLFileVATAdvNotif.al
The new version of ELSTER and ERiC (version 31.4.2.0) is only accepting UTF-8 formatted XML files for Sales Adv. VAT Notification. All other parts are absolutly the same, but ISO-xxx XML files are declined.
Just changed to notation in the XML header.
=> ERiC version 31 is using UTF-8 formatted XML.

Modules/System/Assisted Setup/src/AssistedSetup.Codeunit.al, Modules/System/Assisted Setup/src/AssistedSetupImpl.Codeunit.al
Procedures to remove deprecated Assisted Setups. 
If the Pages the Assisted Setup record refers to are removed, running the assisted setup will result in a runtime error.
=> Added procedure to remove Assisted Setup

Modules/DevTools/TestFramework/TestRunner/src/TestSuiteMgt.Codeunit.al
Setting LastErrorText as Error Message Preview in Test Method Line
instead of the Error Code which is already used for the Error Code.
=> Set LastErrorText as Error Message Preview

Modules/DevTools/TestFramework/TestRunner/src/ALTestTool.Page.al
After selecting a Test Runner in the AL Test Tool the displayed name is not updated.
=> Set TestRunnerDisplayName after Lookup Test Runner

Modules/System/Cues and KPIs/src/CuesAndKPIs.Codeunit.al, Modules/System/Cues and KPIs/src/CuesAndKPIsImpl.Codeunit.al
With this change it is possible to dynamically decide on the Cue Style using enum "Cues And KPIs Style" but regardless of the the decimal Cue Value. 
Explanation: The Cue should be shown in red if there are some rejected entries behind the Document Count.
Example: The Cue shows Number 10 indicating that there are 10 Documents involved. Out of those 10 any or all of those 10 could be critical or marked as rejected and needs checking out first. So only in this case the Cue should have a Style 'Unfavorable'.
=> Publisher OnBeforeGetCustomizedCueStyleOption in Codeunit 9702

Modules/DevTools/TestFramework/TestLibraries/Any/src/Any.Codeunit.al
Sometimes `Any.DecimalInRange` returned a decimal number, whose No. of decimal places did not equal the parameter.
This now has been fixed in accordance with @nikolakukrika. It should be ported afterwards to library random.
The variable name `pow` has been chosen in accordance to `procedure DecimalInRange(MinValue: Decimal; MaxValue: Decimal; DecimalPlaces: Integer): Decimal`.
I am unsure, but it looks like `procedure DecimalInRange(MinValue: Decimal; MaxValue: Decimal; DecimalPlaces: Integer): Decimal` might need a fix as well.
Please refer to https://www.yammer.com/dynamicsnavdev/threads/857565538000896 for further information.
=> Any.DecimalInRange fixed

Modules/System Tests/Cryptography Management/src/DESCryptoServiceProviderTest.Codeunit.al, Modules/System/Cryptography Management/src/DESCryptoServiceProvider.Codeunit.al, Modules/System/Cryptography Management/src/DESCryptoServiceProviderImpl.Codeunit.al
Hi @PredragMaricic and @JesperSchulz,
I added the Salt to the EncryptStream + DecryptStream. Can you please review these and merge the changes to both BC15 and BC16?
I saw the test functions for these two were also missing here in Github, but I did provide them earlier to @PredragMaricic by e-mail, so they should be in your own repository. I did add the salt in the test functions as well.
=> Added the Salt parameter to EncryptStream + DecryptStream

Modules/System Tests/XML Validation/src/XmlValidationTest.Codeunit.al, Modules/System/XML Validation/src/XmlValidationImpl.Codeunit.al
Strip the text 'A call to System.Xml.XmlDocument.Validate failed with this message' from the error message
Before:
After:
=> Throw inner exception message

Modules/System/Email/src/Scenario/EmailScenarioImpl.Codeunit.al
When choosing the Email Scenario then instead of Caption the Name of Enum values is shown.
Before the change (names with prefix XXX):
and after then change (captions):
=> Fix to show caption instead of name when choosing the Email Scenario

Apps/CH/SwissQRBill/app/src/core/Buffer.Table.al, Apps/CH/SwissQRBill/app/src/core/Mgt.Codeunit.al
Hello, I would like to propose removing the internal access modifier of the procedures AddBufferRecord, InitBuffer, SetSourceRecord and GenerateImage. We need to access these in an extension to create a specialized QR Report for a customer.
=> Revealing Procedures related to the QR-Report for Extension Development

Modules/DevTools/TestFramework/TestRunner/src/ALTestTool.Page.al, Modules/DevTools/TestFramework/TestRunner/src/TestSuiteMgt.Codeunit.al
I have added a dialog box to the Get and Update Test actions of the Test Runner Module because I have noticed that when you select all the codeunits it takes a long time and the system is completely blocked without the user being able to know what is really happening.
I hope you find it useful to do the merge.
=> Show Dialogs in some TestRunner long-running actions

Modules/System/Assisted Setup/src/AssistedSetupImpl.Codeunit.al
Dear Team,
Today @ajkauffmann showed me an issue that is related to translations of Assisted Setup. The same issue I face.
When the function AddTranslation is run before it the GlobalLanguage need to be changed to language which should be translated to get translation from 
```
GlobalLanguage(1030);
AssistedSetup.AddTranslation(Page::"My Page", 1030, MyPageAssistedNameLbl);
AssistedSetup.AddTranslation(Page::"My Page 2", 1030, MyPage2AssistedNameLbl);
```
It means that the line in the code 
`
if LanguageID <> GlobalLanguage() THEN
`
Always will be false - we run function with already changed language to the same as sent in the function.
I hope you can approve below quick fix which delete the checking for language id before insert. 
Best Regards,
Krzysztof
=> Issue with translation in Assisted Setup

Apps/W1/APIV2/app/src/pages/APIV2PurchaseInvoices.Page.al, Apps/W1/APIV2/app/src/pages/APIV2SalesCreditMemos.Page.al, Apps/W1/APIV2/app/src/pages/APIV2SalesInvoices.Page.al, Apps/W1/APIV2/app/src/pages/APIV2SalesOrders.Page.al, Apps/W1/APIV2/app/src/pages/APIV2SalesQuotes.Page.al
Dimensions are placed after the lines in sales and purchase document APIs. Because of that, a deep insert with dimensions and lines will create the lines first and then the dimensions on the document. As a result, the lines do not inherit the dimensions from the header, while that is default behavior.
When inserting lines individually this works as expected. But the order in which lines and dimensions are defined in the API prevents this for deep inserts. The only workaround is to include the dimensions on the individual lines as well.
Moving up the dimensions before the lines solves this issue.
See also this thread on Yammer: https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=1085532101779456
=> Move dimensions before lines

Apps/CZ/CoreLocalizationPack/app/Src/Enums/CreditMemoType.Enum.al
If the value is "" it cannot be used in the AL code. Standard for BC is that empty value is " " (one space) not "".
If used in al code, you get error:
```
'"Credit Memo Type CZL"' does not contain a definition for ' '
```
=> (fix): 0 value name changed from "" to " "

Modules/DevTools/BusinessCentralPerformanceToolkit/src/BCPTImportExport.xmlport.al
In our devops pipelines we import a standard suite. And with this suite we are using parameters.
So we need the field parameters and tag in our import to get more detail for analyses and parameters to set the right parameters and not only the standard parameters.
@BardurKnudsen you now we work with parameters :)
=> Added Tag and Parameters in BCPT Import/Export

Apps/CZ/CoreLocalizationPack/app/Src/TableExtensions/VATAmountLine.TableExt.al
VAT Specification shows incorrect LCY values when multiple vat identifiers are present on the document
In document shown on screenshots LCY is CZK.
Broken baseapp functionality:
Fixed:
This error broke VAT Specification table on multiple CZL reports like Posted Sales Invoice, Posted Cr. Memo, etc.
=> VAT Specification shows incorrect LCY values

.github/workflows/Build.yml, Modules/System Tests/Email/src/EmailMessageUnitTest.Codeunit.al, Modules/System/Email/src/Email/EmailImpl.Codeunit.al, Modules/System/Email/src/Email/Outbox/EmailEditor.Codeunit.al, Modules/System/Email/src/Message/EmailMessage.Codeunit.al, Modules/System/Email/src/Message/EmailMessageImpl.Codeunit.al
**Problem:**
It is not possible to send emails from BC if there is no email address in the "To" field.
**Solution:**
Change the validation logic so that it's enough to have at least one recipient in either of the fields: "To", "CC", "BCC"
=> Allow sending emails without the "To" recipients

Modules/System/Cryptography Management/src/Xml/SignedXml.Codeunit.al, Modules/System/Cryptography Management/src/Xml/SignedXmlImpl.Codeunit.al, Modules/System/DotNet Aliases/src/dotnet.al
This adds the possibility to Add Object Element to the SignedXml and it simply uses method AddObject from SignedXml DotNet.
There was DataObject DotNet missing in the DotNet Aliases, that is why I have added the "System.Security.Cryptography.Xml.DataObject" under "System.Security" assembly.
=> Add the possibility of using AddObject method

Modules/System/Default Role Center/README.md
There is a mismatch between the code example and the API definition few lines below.
=> Fixed code sample: RoleCenterId is by reference

Modules/System Tests/Regex/src/RegexTests.Codeunit.al, Modules/System/Regex/src/Regex.Codeunit.al, Modules/System/Regex/src/RegexImpl.Codeunit.al
Often Regex needs subsequent calls with the same pattern and options. This PR allows to pass pattern and options to the constructor and offers additional procedures working on that prepared instance.
I have added 2 Test procedures at the end to allow a performance comparision. Using the same Regex DotNet instance wth the same pattern reduced the runtime by factor 60+ (from 1000 down to 15 milliseconds for 100 matches).
Added Regex() constructors
Added instance specific procedures
Added instance tests
=> Regex allowing precompiled patterns for subsequent calls

Modules/System/Printer Management/src/PrinterManagement.Page.al, Modules/System/Printer Management/src/PrinterSetup.Codeunit.al, Modules/System/Printer Management/src/PrinterSetupImpl.Codeunit.al
Adds (exposes) a `GetPrinterType` procedure to the `"Printer Setup"` codeunit.
Restricted to `[Scope('OnPrem')]`. 
To be used for On-Premise extensions, as a more stable alternative to copying the implementation of `GetPrinterCategory` in the `"Printer Setup Impl."` codeunit.
Addresses #7549.
=> Add GetPrinterType procedure to Printer Setup

Modules/System Tests/Image/src/ImageTests.Codeunit.al, Modules/System/Image/README.md, Modules/System/Image/src/Image.Codeunit.al, Modules/System/Image/src/ImageImpl.Codeunit.al
This PR is related to issue #15162. It adds a new procedure called SetFormat in the module Image.
This procedure allows the user to change the format of the image typically to re-encode a BMP to PNG or PNG to JPEG.
=> New SetFormat in module Image

Modules/System Tests/Azure Blob Services API/src/ABSBlobClientTest.Codeunit.al, Modules/System Tests/Azure Blob Services API/src/ABSContainerClientTest.Codeunit.al, Modules/System/Azure Blob Services API/src/ABSBlobClient.Codeunit.al, Modules/System/Azure Blob Services API/src/ABSClientImpl.Codeunit.al, Modules/System/Azure Blob Services API/src/ABSContainerClient.Codeunit.al, Modules/System/Azure Blob Services API/src/ABSOperationResponse.Codeunit.al, Modules/System/Azure Blob Services API/src/API Enums/ABSLeaseAction.Enum.al, Modules/System/Azure Blob Services API/src/Helper/ABSOptionalParameters.Codeunit.al
This PR adds support for [Lease Blob](https://docs.microsoft.com/en-us/rest/api/storageservices/lease-blob)- and [Lease Container](https://docs.microsoft.com/en-us/rest/api/storageservices/lease-container)-operations for the "Azure Blob Services API".
The tests contain one deactivated part, because the operation ("Lease Change") works against a "real" Azure Storage Account, but not against the Azurite emulator (I'll try to create a PR for the bug in Azurite as well).
=> Add support for Lease operations on Blobs and Containers

Modules/System Tests/BLOB Storage/src/TempBlobTest.Codeunit.al, Modules/System/BLOB Storage/src/TempBlob.Codeunit.al
It would be useful if the Create*Steam functions returned the stream directly so that it can be passed on directly into a convert function, for example.
=> TempBlob Create*Stream with a stream as return

Modules/System Tests/Email/src/EmailMessageUnitTest.Codeunit.al, Modules/System/Email/src/Message/EmailMessage.Codeunit.al, Modules/System/Email/src/Message/EmailMessageImpl.Codeunit.al
per #16149
Adding the following setter functions to the email message codeunit.
- SetBody
- AppendToBody
- SetSubject
- SetBodyHTMLFormatted
- SetRecipients (Both List of Text and Text)
Also renaming the previous setter functions in the codeunit "email message impl" to for example setBodyValue to not have conflicts with the naming in the "email message" codeunit
=> Add setter functions for email message

Modules/DevTools/TestFramework/TestLibraries/Any/src/Any.Codeunit.al
Added 'SetDefaultSeed' that allows to initialize the instance with the same seed that a call to the system function `Randomize` would. This allows to generate non-predictable random numbers - without explicitly specifying a seed.
=> Add 'SetDefaultSeed'

.github/workflows/Build.yml
My Latest PR didn't trigger the CI.
I updated PR Branch Name from old name master to main.
This change will only be used for new PR, as soon as this change is merged to the main branch.
=> Update pull_request_target Branch Name to main

Apps/W1/HybridGP/app/Permissions/HybridGPEdit.PermissionSet.al, Apps/W1/HybridGP/app/Permissions/HybridGPObjects.PermissionSet.al, Apps/W1/HybridGP/app/Permissions/HybridGPRead.PermissionSet.al, Apps/W1/HybridGP/app/Permissions/d365basicHGP.permissionsetext.al, Apps/W1/HybridGP/app/Permissions/d365basicisvHGP.permissionsetext.al, Apps/W1/HybridGP/app/Permissions/d365teammemberHGP.permissionsetext.al, Apps/W1/HybridGP/app/Permissions/intelligentcloudHGP.permisisonsetextension.al, Apps/W1/HybridGP/app/src/Migration/Support/GPConfiguration.table.al, Apps/W1/HybridGP/app/src/Migration/Support/HelperFunctions.codeunit.al, Apps/W1/HybridGP/app/src/Migration/Vendors/GPPM00100.Table.al, Apps/W1/HybridGP/app/src/Migration/Vendors/GPPM00200.Table.al, Apps/W1/HybridGP/app/src/Migration/Vendors/GPVendorMigrator.codeunit.al, Apps/W1/HybridGP/app/src/codeunits/GPCloudMigration.codeunit.al, Apps/W1/HybridGP/app/src/pages/GPMigrationSettingsList.page.al, Apps/W1/HybridGP/app/src/tables/GPCompanyAdditionalSettings.table.al, Apps/W1/HybridGP/test/src/GPDataMigrationTests.codeunit.al
This change enhances the GP cloud migration to include migrating GP Vendor Classes to BC Vendor Posting Groups.
- For each GP vendor class that has related accounts a new Vendor Posting Group will be created in BC.
- Any vendor migrated from GP that is part of a vendor class will have the related Vendor Posting Group assigned.
- A configuration option has been added to give the ability to not migrate Vendor Classes, disabled by default.
=> Migrate GP Vendor Classes

Apps/W1/HybridGP/app/Permissions/HybridGPEdit.PermissionSet.al, Apps/W1/HybridGP/app/Permissions/HybridGPObjects.PermissionSet.al, Apps/W1/HybridGP/app/Permissions/HybridGPRead.PermissionSet.al, Apps/W1/HybridGP/app/Permissions/d365basicHGP.permissionsetext.al, Apps/W1/HybridGP/app/Permissions/d365basicisvHGP.permissionsetext.al, Apps/W1/HybridGP/app/Permissions/d365teammemberHGP.permissionsetext.al, Apps/W1/HybridGP/app/Permissions/intelligentcloudHGP.permisisonsetextension.al, Apps/W1/HybridGP/app/src/Migration/Customers/GPCustomerMigrator.codeunit.al, Apps/W1/HybridGP/app/src/Migration/Customers/GPRM00101.Table.al, Apps/W1/HybridGP/app/src/Migration/Customers/GPRM00201.Table.al, Apps/W1/HybridGP/app/src/Migration/Support/GPConfiguration.table.al, Apps/W1/HybridGP/app/src/Migration/Support/HelperFunctions.codeunit.al, Apps/W1/HybridGP/app/src/codeunits/GPCloudMigration.codeunit.al, Apps/W1/HybridGP/app/src/pages/GPMigrationSettingsList.page.al, Apps/W1/HybridGP/app/src/tables/GPCompanyAdditionalSettings.table.al, Apps/W1/HybridGP/test/src/GPDataMigrationTests.codeunit.al
This change enhances the GP cloud migration to include migrating GP Customer Classes to BC Customer Posting Groups.
- For each GP customer class that has related accounts a new Customer Posting Group will be created in BC.
- Any customer migrated from GP that is part of a customer class will have the related Customer Posting Group assigned.
- A configuration option has been added to give the ability to not migrate Customer Classes, disabled by default.
=> Migrate GP Customer Classes

Apps/W1/MicrosoftUniversalPrint/src/UniversalPrintDocumentReady.Codeunit.al
Removed "internal" specifier from UniversalPrintDocumentReady.SendPrintJob() to allow easy printing of external documents.
Works eg. by calling
UniversalPrinterSettings.Get('PRINTERNAME');
UploadIntoStream('Title', '', '', FromFile, InStr);
UniversalPrintDocumentReady.SendPrintJob(UniversalPrinterSettings, InStr, 'Best Document', 'pdf', 'application/pdf')
=> Make SendPrintJob() externally accessible

Apps/W1/HybridGP/app/src/Migration/Accounts/GPAccountMigrator.codeunit.al
Currently the migration tool brings across all monthly summary transactions and assigns them all the same document number: G00001. This number can make it difficult when trying to reconcile with GP. Instead, will use the Batch Name value for Document No. making it unique across batches.
=> Change document number

Apps/W1/HybridGP/app/src/Migration/Support/HelperFunctions.codeunit.al, Apps/W1/HybridGP/app/src/Migration/Support/PurchaseOrders/GPPOMigrator.codeunit.al, Apps/W1/HybridGP/app/src/Migration/Support/PurchaseOrders/GPPOPPOHeader.table.al, Apps/W1/HybridGP/app/src/Migration/Support/PurchaseOrders/GPPOPPOLine.table.al, Apps/W1/HybridGP/test/src/GPDataMigrationTests.codeunit.al
This change fixes an issue where the GP migration would fail if an Open PO contains a non-inventory item that has a unit of measure not set up in GP (added via free text on the PO line).
- Moved the PO migration code out of the tables and to a new Codeunit.
- It creates the Unit of Measure if it doesn't exist.
=> GP - PO Non-Inventory missing UofM fix

Modules/System/Azure Blob Services API/src/Helper/ABSOptionalParameters.Codeunit.al
In the module Azure Blob Service Api it is possible to set HTTP Header via the predefined codeunit "ABS Optional Parameters". When using the "Range" function, a label is used that does not have locked = true. This means that the translation is always used when setting the HTTP header. The problem is that in some XLF files the translation is different from the caption, so the HTTP request runs into an error. (e.g. in the German translation)
=> Add "Locked = true" to HttpHeader Labels

Modules/System/Cryptography Management/src/CryptographyManagement.Codeunit.al, Modules/System/Cryptography Management/src/CryptographyManagementImpl.Codeunit.al
In Cryptography Management the option for using Signature Key(codeunit) as the private key exists for the SignData procedure which takes both xml string and Signature key. But not for VerifyData it only has a xml string option but i don´t see why it should not also be possible to use Signature Key(codeunit) for VerifyData. Since the only Cloud friendly way to retrieve a Privatekey from Certificates is via 
Certificate Management.GetCertPrivateKey(IsolatedCertificate: Record "Isolated Certificate"; var SignatureKey: Codeunit "Signature Key") 
This is a step towards making the LS Central app universal code compliant.
=> Add VerifyData procedure with SignatureKey as PrivateKey to Cryptography Management

.github/RELEASENOTES.copy.md, .github/workflows/AddExistingAppOrTestApp.yaml, .github/workflows/CICD.yaml, .github/workflows/CreateApp.yaml, .github/workflows/CreateOnlineDevelopmentEnvironment.yaml, .github/workflows/CreatePerformanceTestApp.yaml, .github/workflows/CreateRelease.yaml, .github/workflows/CreateTestApp.yaml, .github/workflows/Current.yaml, .github/workflows/IncrementVersionNumber.yaml, .github/workflows/NextMajor.yaml, .github/workflows/NextMinor.yaml, .github/workflows/PublishToEnvironment.yaml, .github/workflows/PullRequestHandler.yaml, .github/workflows/UpdateGitHubGoSystemFiles.yaml, Modules/.AL-Go/cloudDevEnv.ps1, Modules/.AL-Go/localDevEnv.ps1
Note that when using the preview version of AL-Go for GitHub, you need to Update your AL-Go system files, as soon as possible when told to do so.
- Issue #233 AL-Go for GitHub causes GitHub to issue warnings
- Issue #244 Give error if AZURE_CREDENTIALS contains line breaks
- New workflow: PullRequestHandler to handle all Pull Requests and pass control safely to CI/CD
- Changes to yaml files, PowerShell scripts and codeowners files are not permitted from fork Pull Requests
- Test Results summary (and failed tests) are now displayed directly in the CI/CD workflow and in the Pull Request Check
- Proof Of Concept Delivery to GitHub Packages and Nuget
- Issue #143 Commit Message for **Increment Version Number** workflow
- Issue #160 Create local DevEnv aith appDependencyProbingPaths
- Issue …
=> 'Updated AL-Go System Files'

Modules/.AL-Go/settings.json
Running tests is currently halting the runners and rendering CICD pipeline to fail.
Running tests will be re-enabled once the jobs are stable.
=> Skip running tests

Apps/W1/HybridGP/app/src/pages/HybridCloudWizardExtension.PageExt.al
Clean up the GP migration settings for companies that have already been migrated. This issue was found while going through a subsequent migration test for another company after a previously successful migration.
=> Clean up GP migration settings for any companies previously migrated

Modules/DevTools/TestFramework/TestRunner/src/TestSuiteMgt.Codeunit.al
Action "Update Test Methods" in AL Test Tool resets filters on the page, mixing test codeunit from different suites
Steps to reproduce
Run AL Test Tool and pull a test codeunit into the Default test suite
Create another test suite and get a test codeunit
Run Update Test Methods action
Result: Test codeunits from all suites are displayed, page filters are lost.
Expected result: The action should keep the filters.
Issue: Functions GetView/SetView which are used to copy filters between record instances only pick filters in the active filter group (currently 0), while the suite filter is applied in group 2.
Solution: Use CopyFilters instead, which copies filters in all groups.
=> Copy filters on test suite update

Modules/System Tests/Azure Storage Services Authorization/src/StorServAccountSASTest.Codeunit.al, Modules/System/Azure Storage Services Authorization/src/SAS/SASPermission.Enum.al
I tried to add the missing permission types for SAS Authentication of the azure storage authentication.
Reference: https://learn.microsoft.com/en-us/rest/api/storageservices/create-account-sas#specify-the-account-sas-parameters
=> Add new permission Types for SAS

Modules/System/SharePoint Authorization/src/AuthorizationCode/SharePointAuthorizationCode.Codeunit.al
- IsSuccess never received a value from OAuth2.AcquireTokenByAuthorizationCode.
- Changed "Prompt Interaction"::Login to "Prompt Interaction"::None. Otherwise, you always need to login again. Now, you can select an account already signed in.
=> Fix SharePoint AcquireToken

.github/RELEASENOTES.copy.md, .github/workflows/AddExistingAppOrTestApp.yaml, .github/workflows/CICD.yaml, .github/workflows/CreateApp.yaml, .github/workflows/CreateOnlineDevelopmentEnvironment.yaml, .github/workflows/CreatePerformanceTestApp.yaml, .github/workflows/CreateRelease.yaml, .github/workflows/CreateTestApp.yaml, .github/workflows/Current.yaml, .github/workflows/IncrementVersionNumber.yaml, .github/workflows/NextMajor.yaml, .github/workflows/NextMinor.yaml, .github/workflows/PublishToEnvironment.yaml, .github/workflows/PullRequestHandler.yaml, .github/workflows/UpdateGitHubGoSystemFiles.yaml, Modules/.AL-Go/localDevEnv.ps1
Note that when using the preview version of AL-Go for GitHub, you need to Update your AL-Go system files, as soon as possible when told to do so.
- Issue #312 Branching enhancements
- Issue #229 Create Release action tags wrong commit
- Issue #283 Create Release workflow uses deprecated actions
AL-Go projects can now be built in different modes, by specifying the _buildModes_ setting in AL-Go-Settings.json. Read more about build modes in the [Basic Repository settings](https://github.com/microsoft/AL-Go/blob/main/Scenarios/settings.md#basic-repository-settings).
Continuous Delivery can now run from other branches than main. By specifying a property called branches, containing an array of branches in the deliveryContext json construct, the artifacts generated from this branch are also …
=> Updated AL-Go System Files

Modules/System/SharePoint Authorization/README.md, Modules/System/SharePoint Authorization/src/AuthorizationCode/SharePointAuthorizationCode.Codeunit.al
After some fighting to get the SharePoint module to work, I want to improve the SharePoint Authorization module with my findings.
1. Improved the README.md file
- Added information and examples of API Permissions and Scope needed to get the authorization to work.
- Corrected the syntaxes of the functions
2. Added support for Token Cache when acquiring an Access Token
- This removes unnecessary popups of the authorization window, and I believe it is faster
- This makes it possible to schedule jobs that works against SharePoint, as long as the user is authenticated now and then (I believe the default life for a Refresh Token is 3 months)
3. Removed the custom caching of Access Token.
- "SharePoint Authorization Code" had implemented it's own caching of the Access Token, with a hardcoded …
=> SharePoint Auth - Improved README and use the Token Cache

Apps/W1/HybridGP/app/Permissions/HybridGPEdit.PermissionSet.al, Apps/W1/HybridGP/app/Permissions/HybridGPObjects.PermissionSet.al, Apps/W1/HybridGP/app/Permissions/HybridGPRead.PermissionSet.al, Apps/W1/HybridGP/app/Permissions/INTELLIGENTCLOUDHGP.PermissionSetExt.al, Apps/W1/HybridGP/app/Permissions/d365basicHGP.permissionsetext.al, Apps/W1/HybridGP/app/Permissions/d365basicisvHGP.permissionsetext.al, Apps/W1/HybridGP/app/Permissions/d365teammemberHGP.permissionsetext.al, Apps/W1/HybridGP/app/src/Migration/Support/HelperFunctions.codeunit.al, Apps/W1/HybridGP/app/src/Migration/Support/PurchaseOrders/GPPOMigrator.codeunit.al, Apps/W1/HybridGP/app/src/Migration/Support/PurchaseOrders/GPPOP10100.table.al, Apps/W1/HybridGP/app/src/Migration/Support/PurchaseOrders/GPPOP10110.table.al, Apps/W1/HybridGP/app/src/Migration/Support/PurchaseOrders/GPPOPPOHeader.table.al, Apps/W1/HybridGP/app/src/Migration/Support/PurchaseOrders/GPPOPPOLine.table.al, Apps/W1/HybridGP/app/src/Migration/Vendors/GPVendorMigrator.codeunit.al, Apps/W1/HybridGP/app/src/codeunits/GPCloudMigration.codeunit.al, Apps/W1/HybridGP/test/src/GPDataMigrationTests.codeunit.al
This change fixes a few issues with migrating open POs from GP.
- Replaced the PO header and line tables. The new tables contain only fields that are used (or may be used in the near future), have the updated naming convention, and without the TIME1 field that was causing errors when a DateTime was included in that field.
- Added the PO filter that was missing after the SQL statements were removed.
- Added a missing .Init() statement when looping PO headers to insert.
- Fixed an issue where the originating currency wasn't migrated if it was in a non-default currency.
=> GP - Fix recent issues with POs

.github/workflows/CreateBuildTag.yaml
Issue: _CreateBuildTag_ workflow run after the CICD completed successfully. However, CICD works on PRs as well so _CreateBuildTag_ is running in the PR branch is also _main_ (from a fork). 
Solution: Limit the _TagSuccessfulBuild_ job to only run on the main repo.
=> Do not create build tags on forks

Apps/W1/ConnectivityApps/app/src/Codeunits/ConnectivityAppDefinitions.Codeunit.al
With the release of BC 21 the app name was changed to align with the remaining Continia product suite. This was not reflected in the ConnectivityApps .
@microsoft-github-policy-service agree company="Continia Software"
=> Corrected ConnectivityApp name to match actual app name.

Modules/.AL-Go/NewBcContainer.ps1
Users were not created and the container auth was set to _Windows_ in order for the tests to pass.
However, using _Windows_ auth with no users causes issues when setting up local dev environment.
Fixing the tests will be addressed separately.
=> Fix localDevEnv: Do not skip user creation

Modules/System/Cryptography Management/README.md, Modules/System/Cryptography Management/src/Xml/SignedXml.Codeunit.al, Modules/System/Cryptography Management/src/Xml/SignedXmlImpl.Codeunit.al
Added method AddReferenceToSignedXML.
Gives us possibility to add multiple reference to Signed XML object.
=> Add reference to Signed XML method

Build/Scripts/GuardingV2ExtensionsHelper.psm1
**Problem**
If you add a new app there is no baseline yet. Currently this means the build job will fail because we can't restore the baseline 
**Solution**
Allow building applications even when restoring the baseline fails
=> Allow build even when restoring baselines fail

Build/Scripts/EnlistmentHelperFunctions.psm1, Build/Scripts/GuardingV2ExtensionsHelper.psm1
Cache baseline packages so they're only downloaded once per job. 
Right now we download the same baseline package every time we invoke CompileAppInBcContainer. This happens 5 times in the "Build Test Framework" task, so this PR would reduce that to downloading it once.
=> Cache baseline packages 

Apps/W1/Shopify/app/src/Products/Tables/ShpfyShopCollectionMap.Table.al
The length of the field Product Group Code in the table  "Shpfy Shop Collection Map" was 10. Which gave the error with longer VAT Product Posting Groups.
It was possible to add the VAT Product Posting Group more than 10 chars but there was an issue when renaming the value.
I checked where the field is used and looks like there are no references in Shopify Connector that would break anything else.
=> Fix length of Product Group Code in Shopify Connector

Build/Scripts/AppTranslations.psm1, Build/Scripts/CompileAppInBcContainer.ps1, Build/Scripts/EnlistmentHelperFunctions.psm1
- Fix package name 
- Force create `Translations` folder when restoring translations
CICD on branch succeeded: https://github.com/microsoft/ALAppExtensions/actions/runs/4919277665
=> Fix translated build jobs

Modules/System/SharePoint/src/SharePointClient.Codeunit.al, Modules/System/SharePoint/src/SharePointClientImpl.Codeunit.al, Modules/System/SharePoint/src/helpers/SharePointRequestHelper.Codeunit.al
Adds DownloadFileContent() overloads to SharePoint client
Adds new functions DeleteFile() and DeleteFolder() to SharePoint client
This PR can replace PR #22565 and PR #22402 as discussed with @pri-kise and @jwikman in PR #22402
=> SharePoint library add functions and function overloads

Modules/System Tests/Azure Blob Services API/src/ABSBlobClientTest.Codeunit.al, Modules/System/Azure Blob Services API/src/ABSBlobClient.Codeunit.al, Modules/System/Azure Blob Services API/src/ABSClientImpl.Codeunit.al, Modules/System/Azure Blob Services API/src/ABSOperationResponse.Codeunit.al, Modules/System/Azure Blob Services API/src/Helper/ABSContainerContentHelper.Codeunit.al, Modules/System/Azure Blob Services API/src/Helper/ABSHelperLibrary.Codeunit.al, Modules/System/Azure Blob Services API/src/Helper/ABSOptionalParameters.Codeunit.al
Return of NextMarker so it is possible to use paging an select more than the first 5000 Blobs
Preformance optimized so collection of 5000 Blobs goes from 45 sec. to  around 9 sec. when using "ABS Container Content" table
Using new overload on ListBlobs will return a dictionary instead of "ABS Container Content" table and the time goes down to 2 sec.
All measurements are based on a local Sandbox Container version 21.5.53619.54870
=> Nextmarker And ListBlobs overload

Apps/W1/APIReportsFinance/App/src/APIFinCustLedgEntry.Query.al, Apps/W1/APIReportsFinance/App/src/APIFinVendLedgEntry.Query.al, Apps/W1/APIReportsFinance/App/src/APIFinanceGLEntry.Query.al
In APIReportsFinance the Customer/Vendor/GL Entries have wrong field for externalDocumentNo, it shows Document No. instead of External Document No.
=> Wrong field APIReportsFinance- external document no.

Modules/System/Permission Sets/src/PermissionImpl.Codeunit.al
**🕮 Describe the issue**
When user creates new permission for a certain permission set, the default values for Table Data are to generous. Only "read permission" should be defaulted to Yes during record initialization. Currently insert, modify and delete are also defaulted to Yes.
**🔧 To Reproduce**
Steps to reproduce the behavior:
1. Go to Permission Sets
2. Click on any user defined permission set or create a new one.
3. Open page permissions
4. Click on "New Line" on permissions subpage.
5. enter some table id, for example 3 (Payment Terms)
6. Observe that all permission types - read, insert, modify and delete are defaulted to Yes
**📣 Expected behavior**
Only Read Permission should be defaulted to Yes and the user can set other permission types to Yes if needed. Similar to the function …
=> default values for Permissions with Type=TableData

Modules/System/Azure Storage Services Authorization/src/ReadySAS/StorServAuthReadySAS.Codeunit.al, Modules/System/Azure Storage Services Authorization/src/SAS/StorServAuthSAS.Codeunit.al, Modules/System/Azure Storage Services Authorization/src/StorServAuthImpl.Codeunit.al, Modules/System/Azure Storage Services Authorization/src/StorageServiceAuthorization.Codeunit.al
- Add new authorization option to use pre-generated SAS Token.
This allows to use a token that was generated directly in azure portal, the benefit is that we don't have to store storage account key in BC.
- Fix unnecessary '&' being appended to query text if there weren't any parameters in the query in SAS authorization.
=> Add ready SAS authorization

.github/ISSUE_TEMPLATE/create-issue-i-want-to-address.md, .github/ISSUE_TEMPLATE/feature_request.md, CONTRIBUTING.md
Aligning process for contributions with the BusinessCentralApps repository. Going forward, larger feature contributions must be based on BC Ideas, while smaller issues must use the provided template.
=> Add issue templates and contribution guidelines.

Apps/W1/Shopify/README.md, Apps/W1/Shopify/app/src/Payments/Tables/ShpfyPaymentTransaction.Table.al, Apps/W1/Shopify/app/src/Payments/Tables/ShpfyPayout.Table.al
Hi,
This change allows users / developers to develop their own code to apply the payouts directly to customer ledger entries.
Right now, payouts are for information purposes only, which is not ideal.
There is a function on the page (listpart 30124) which makes us able to throw the data out into Excel – but this seems rather problematic to make a function for this instead of directly getting the data from the table.
Just to make sure, i am currently talking about current tables:
- 30124
- 30125
=> [Shopify] Remove access internal from Payment tables

Modules/System/Azure Blob Services API/README.md, Modules/System/Azure Blob Services API/src/ABSBlobClient.Codeunit.al, Modules/System/Azure Blob Services API/src/ABSClientImpl.Codeunit.al, Modules/System/Azure Blob Services API/src/ABSContainerClient.Codeunit.al, Modules/System/Azure Blob Services API/src/Helper/ABSHttpContentHelper.Codeunit.al
The intent of this change is to extend PutBlobBlockBlobStream and PutBlobBlockBlobText procedures with ContentType parameter.
=> Extend Azure Blob Services API with Content Type

Modules/System Tests/Permission Sets/src/UpdatingPermissionTests.Codeunit.al, Modules/System/Permission Sets/src/PermissionImpl.Codeunit.al, Modules/System/Permission Sets/src/TenantPermissionSubForm.page.al
The goal is to introduce the actions that existed on the page that is marked as obsoleted and named "Permissions (legacy)" on a page listing all permission sets. Processing multiple objects in a batch was highly appreciated feature so far.
How it looked on a paged marked for obsoletion:
How it is desired to look a new permission set card page:
=> actions for processing multiple permissions

Apps/W1/HybridGP/app/src/Migration/Support/PurchaseOrders/GPPOMigrator.codeunit.al
This change fixes multiple issues found while attempting to migrate open Purchase Orders during a GP migration.
Fixes
- Prevent migrating the PO if the Vendor Id is empty (bad data)
- Vendor Posting Group set by the Vendor, not hard coded to "GP".
- Better line over-receipt support
- Line count fixes
- Add the Vendor Invoice No. if available. 
- Post the Purchase Order with received lines, which creates Purchase Receipt and related posting records to prevent a failure when later manually posting the Purchase Order
=> GP PO fixes - 2nd attempt

Modules/System/Azure Blob Services API/src/Helper/ABSHttpContentHelper.Codeunit.al
I fix the HttpHeaders of the Content.
This was a bug introduced in BC20 by fixing the vairable names.
CommitID: 6f7bd47e19261df4200689741d0a2c6248e89991
Additional i refactor to new Length Method of Stream.
=> Azure Blob Storage - Fix Content Headers

Apps/W1/HybridGP/app/src/Migration/Accounts/GPAccountMigrator.codeunit.al, Apps/W1/HybridGP/app/src/Migration/History/GPPOPReceiptApply.table.al, Apps/W1/HybridGP/app/src/Migration/Support/PurchaseOrders/GPPOMigrator.codeunit.al
This hotfix PR corrects issues with PO lines and missing Beginning Balance dimensions.
PO Changes
- Add Location Code association on the Negative Adjustment lines
- Correct line Unit Cost and calculate Extended Cost
- Split lines per receipt line to get more accurate Unit Cost per receipt line
GL changes
- Beginning Balance entries were not including the dimensions, this change corrects this.
=> GP July changes to PO migration - Hotfix 2

Apps/W1/StatisticalAccounts/app/src/StatAccFinReportingMgt.Codeunit.al, Apps/W1/StatisticalAccounts/app/src/StatAccReverseEntry.Codeunit.al
- Correction for apply totaling dimensions filters:
The cell value calculation does not apply the totaling dimensions filters, however the drilldown shows the entries with the totaling dimensions filters.
- Allow to reverse entries with HideDialog option
=> Statistical Accounts

Apps/W1/Shopify/app/src/Transactions/Tables/ShpfyOrderTransaction.Table.al
Hi,
For Paypal transactions (indeed anything other than the standard Shopify Gateway) we need to get access to the Authorization field which is currently sat on “Shpfy Order Transaction", however this table is flagged as Internal.
Basically we drop this on to the External Document No. field in a Sales Order to enable it to flow through to the Bank Ledger Entries.
The change will allow to access the data directly from the table.
Since the table contains sensitive information a list of fields marked as Internal:
field(15; "Source Name"; Code[20])
field(16; "Credit Card Bin"; Code[10])
field(17; "AVS Result Code"; Code[1])
field(18; "CVV Result Code"; Code[1])
field(19; "Credit Card Number"; Text[30])
=> [Shopify] Shpfy Order Transaction: removed Access Internal

Modules/System Tests/Email/src/EmailAccountsTest.Codeunit.al, Modules/System/Email/src/Account/EmailAccount.Codeunit.al, Modules/System/Email/src/Account/EmailAccountImpl.Codeunit.al
This PR adds a new method to delete Accounts without UI.
Currently it isn't possible to delete E-Mail Accounts.
With this PR I want to provide the ability to delete e-Mail Accounts via code that we can clean this table On Test/Dev Environments when working with customer data to avoid accidently sending an e-Mail.
Espcecially in OnPrem where we aren't able to trigger the Cleanup Environment triggers.
=> Add Procedure to Delete E-Mail Accounts

Apps/W1/HybridGP/app/src/Migration/Accounts/GPAccountMigrator.codeunit.al
A previous merge placed code in the wrong procedure, which prevented accounts from being created when the migration was configured to only migrate GL master data.
=> GP - Hotfix to correct previous merge issue

Modules/System Tests/Data Compression/src/DataCompressionTests.Codeunit.al, Modules/System/Data Compression/src/DataCompression.Codeunit.al, Modules/System/Data Compression/src/DataCompressionImpl.Codeunit.al
Add new "IsZip" method and new overload for "ExtractEntry". 
@pri-kise haven't got the chance to really test this in the context of the System Application (copied somewhat from another app of mine where I implemented this). Not exactly sure, but I'm having a lot of issues with getting `System.Drawing` (among others) to load properly in this repo, following the getting started guide. Any idea?
=> #24604: Add new "IsZip" method and "ExtractEntry" overload

Apps/W1/DataSearch/App/DataSearchEvents.codeunit.al, Apps/W1/DataSearch/App/DataSearchInTable.codeunit.al
**Issue Description**
The "Search in company data" feature lacks the possibility to filter the results shown to the user.
There are some scenarios where displaying every single record that contains a given **Search String** is not desirable.
While "security filters" are included in the "Data Search," they may be insufficient if you have requirements to manage access to specific tables on a record level for multiple users in various scenarios. In some cases, this would require a consultant to create a separate permission set for each user and thats obviously a lot of effort.
**Solution**
This PR introduces new ```OnBeforeSearchTable``` publisher, which allows to prefilter the ```RecRef``` that is used for searching for the ```SearchString```.
=> Add OnBeforeSearchTable publisher for "Search in company data" feature

Modules/System/Recurrence Schedule/src/RecurrenceScheduleImpl.Codeunit.al
When trying to show a recurrence schedule (and make some changes to it), follow error is raised when closing the `Recurrence Schedule Card`.
---
**CallStack**
"Recurrence Schedule Impl."(CodeUnit 4691).**OpenRecurrenceSchedule** line 20 - System Application by Microsoft
"Recurrence Schedule"(CodeUnit 4690).OpenRecurrenceSchedule line 2 - System Application by Microsoft
"ESCA Recurrence Schedule"(Table 71096653).ShowRecurrenceSchedule line 12 - Dynavision Core by Dynavision
---
**Source of the problem**
---
**Solution**
- Added `modify` permissions on the implementation codeunit
=> Add modify permissions to "Recurrence Schedule"

Apps/W1/APIV2/app/src/pages/APIV2FALocations.Page.al, Apps/W1/APIV2/app/src/pages/APIV2FixedAssets.Page.al, Apps/W1/APIV2/test/src/APIV2FALocationsE2E.Codeunit.al, Apps/W1/APIV2/test/src/APIV2FixedAssetsE2E.Codeunit.al
For one of the community project related to the PowerApp it is needed to have a APIs for Fixed Assets and Fixed Asset Locations. 
Those APIs are needed in standard API collection since. It will also allow more interact with the date inside Business Central (for example create Power Automate flows based on Fixed Assets)
=> APIs for Fixed Assets and Fixed Asset Locations

Apps/W1/EDocument/app/src/Processing/EDocumentSubscription.Codeunit.al
In our BG localization we have a functionality based on Bulgarian legislation that allows to void a posting document. Therefore, during voiding, the header of an posted document is deleted, which is taken with GET without checking in the e-document app. For now we remove e-document for our customers to work with our localization. Please change the code i think it will not cause errors.<br /><br />Internal work item: AB#492530
=> use "if" "then" with get for posted document when calling e-document subscriptions

Apps/W1/HybridGP/app/Permissions/HybridGPEdit.PermissionSet.al, Apps/W1/HybridGP/app/Permissions/HybridGPObjects.PermissionSet.al, Apps/W1/HybridGP/app/Permissions/HybridGPRead.PermissionSet.al, Apps/W1/HybridGP/app/Permissions/INTELLIGENTCLOUDHGP.PermissionSetExt.al, Apps/W1/HybridGP/app/Permissions/d365basicHGP.permissionsetext.al, Apps/W1/HybridGP/app/Permissions/d365basicisvHGP.permissionsetext.al, Apps/W1/HybridGP/app/Permissions/d365teammemberHGP.permissionsetext.al, Apps/W1/HybridGP/app/src/Migration/Accounts/GPAccountMigrator.codeunit.al, Apps/W1/HybridGP/app/src/Migration/Support/GPPaymentTerms.Page.al, Apps/W1/HybridGP/app/src/Migration/Support/GPPaymentTerms.table.al, Apps/W1/HybridGP/app/src/Migration/Support/HelperFunctions.codeunit.al, Apps/W1/HybridGP/app/src/Migration/Support/PurchaseOrders/GPPOMigrator.codeunit.al, Apps/W1/HybridGP/app/src/codeunits/HybridGPWizard.codeunit.al, Apps/W1/HybridGP/app/src/pages/GPCompanyAddSettingsList.Page.al, Apps/W1/HybridGP/app/src/pages/GPMigrationLog.Page.al, Apps/W1/HybridGP/app/src/pages/GPMigrationWarnings.Page.al, Apps/W1/HybridGP/app/src/pages/HybridGPErrorsOverviewFb.page.al, Apps/W1/HybridGP/app/src/pages/HybridGPOverviewFb.Page.al, Apps/W1/HybridGP/app/src/pages/IntelligentCloudExtension.PageExt.al, Apps/W1/HybridGP/app/src/tables/GPCompanyAdditionalSettings.table.al, Apps/W1/HybridGP/app/src/tables/GPMigrationLog.Table.al, Apps/W1/HybridGP/app/src/tables/GPMigrationWarnings.Table.al, Apps/W1/HybridGP/test/src/GPDataMigrationTests.codeunit.al
This PR enhances the GP migration by hardening the code around Payment Terms creation, adds visibility of unposted batches, and a new Migration Log.
This change hardens the code around Payment Term creation. It also includes an integration event so that a failing Payment Term could be created by a PTE if needed.
This change also includes a migration log. A Factbox tile is added to the Cloud Migration Management page that will show the user when a non-error action was taken by the migration app, and they should be made aware of it. 
Currently, these are the scenarios that are now logged:
- The Payment Term was handled by 3rd party code.
- Skipped creating an Account because there isn't an account number.
- Skipped creating a PO because the Vendor has not been migrated.
A Factbox tile is …
=> GP - Enhancements to Payment Terms creation, visibility of unposted batches, and Migration Log

Apps/W1/Shopify/app/src/Order handling/Codeunits/ShpfyImportOrder.Codeunit.al
I've added a line of code that filters the OrderLineAttribute variable on field "Order Line Id". 
The purpose is to avoid deletion of records imported for previous lines.
Fixes #26274 
Fixes [AB#525455](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/525455)
=> Add Order Line Id to OrderLineAttribute in ShpfyImportOrder.Codeunit.al

Apps/W1/DynamicsGPHistoricalData/app/src/Pages/HistPayablesDocuments.Page.al, Apps/W1/DynamicsGPHistoricalData/app/src/Pages/HistPurchaseRecvHeaders.Page.al, Apps/W1/DynamicsGPHistoricalData/app/src/Pages/HistReceivablesDocuments.Page.al, Apps/W1/DynamicsGPHistoricalData/app/src/Pages/HistSalesTrxHeaders.Page.al
This change corrects filtering for some of the history pages. Filters were broken for Customers/Vendors that had an & symbol in their No. field.
Fixes #26487
Fixes [AB#537204](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537204)
=> Correct filtering by using SetRange instead of SetFilter.

Apps/W1/HybridGP/app/src/Migration/Items/GPItemMigrator.codeunit.al, Apps/W1/HybridGP/app/src/Migration/Support/HelperFunctions.codeunit.al
This PR updates the GP migration batch posting to safely run and log any errors instead of fail the migration.
Fixes [AB#537482](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537482)
Fixes #26487
=> GP - Safe Batch Posting

Apps/W1/Shopify/app/src/Inventory/Codeunits/ShpfyInventoryAPI.Codeunit.al
This pull request does not have a related issue as it's part of delivery for development agreed directly with @AndreiPanko 
Quick summary:
We saw that the Sales Unit of Measure should be used for inventory synchronization but there is a bug that prevents it from doing it. In line 61, Item.???Sales Unit Of Measure??? will always be empty, because in the function in line 51, it is cleared. It means that if the statement in line 63 never is true, the Base Unit of Measure will always be used for inventory synchronization.
Fixes #26719
Fixes [AB#539103](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/539103)
=> [Shopify] Integration to use Sales Unit of Measure for inventory synchronization

Apps/W1/Shopify/app/src/Order handling/Codeunits/ShpfyOrderEvents.Codeunit.al, Apps/W1/Shopify/app/src/Order handling/Codeunits/ShpfyOrderMapping.Codeunit.al, Apps/W1/Shopify/app/src/Order handling/Codeunits/ShpfyProcessOrder.Codeunit.al, Apps/W1/Shopify/app/src/Order handling/Pages/ShpfyOrder.Page.al, Apps/W1/Shopify/app/src/Order handling/Tables/ShpfyOrderHeader.Table.al, Apps/W1/Shopify/app/src/Shipping/Pages/ShpfyShipmentMethodsMapping.Page.al, Apps/W1/Shopify/app/src/Shipping/Tables/ShpfyShipmentMethodMapping.Table.al
This pull request does not have a related issue as it's part of delivery for development agreed directly with @AndreiPanko 
Quick summary:
The Shopify Shipping Method Mapping page/table was extended to include a new Shipping Charges Type field, allowing users to select from GL, Item, or Item Charge. Depending on this selection, the Shipping Charges No. field opens the related table (item, GL, or item charges), and when an order is created, the shipping charge line reflects the new type and number. For Item Charges, a default allocation process is run for all item lines. The settings in the Shopify Shipping Method Mapping now take priority over those in the Shopify Shop - GL Account settings. Additionally, if the Shipping Agent Code and Shipping Agent Service fields are populated, they are …
=> [Shopify] Connector - Different shipping charges types

Apps/W1/ConnectivityApps/app/src/Codeunits/ConnectivityAppDefinitions.Codeunit.al
Added US to Yavrio Open Banking
Fixes [AB#543398](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/543398)
=> Update Yavrio in ConnectivityAppDefinitions.Codeunit.al

Apps/W1/EDocument/app/src/Log/EDocumentIntegrationLog.Table.al, Apps/W1/EDocument/app/src/Log/EDocumentIntegrationLogs.Page.al, Apps/W1/EDocument/app/src/Log/EDocumentLog.Codeunit.al, Apps/W1/EDocument/test/src/Log/EDocLogTest.Codeunit.al
Added a new field "Request URL" to table 6127 "E-Document Integration Log" with a maximum string length of 2048 to allow for longer URLs when using the "E-Document Integration" interface. The new filed replaces the existing field URL. I marked the existing field as obsolete and updated three (all) references from the old URL field to the new "Request URL" field.
Fixes #26672
Fixes [AB#540448](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540448)
=> [Fix] URL maximum length in E-Document Integration

Apps/W1/Shopify/app/src/Catalogs/Pages/ShpfyCatalogs.Page.al, Apps/W1/Shopify/app/src/Catalogs/Tables/ShpfyCatalog.Table.al, Apps/W1/Shopify/app/src/Products/Codeunits/ShpfyProductPriceCalc.Codeunit.al, Apps/W1/Shopify/test/Catalogs/ShpfyCatalogPricesTest.Codeunit.al, Apps/W1/Shopify/test/Products/ShpfyProductInitTest.Codeunit.al
Added Customer No to the 
table 30152 "Shpfy Catalog"
page 30159 "Shpfy Catalogs"
Added logic to use customer specific pricing from catalog
codeunit 30182 "Shpfy Product Price Calc."
Fixes #26980
Fixes [AB#544010](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544010)
=> [Shopify][BC Idea]: Enhancing Shopify Connector for Accurate Price Synchronization with Business Central based on Customer

Apps/W1/EDocumentsConnector/app/src/E3Party/EDocExtConnectionSetupCard.Page.al, Apps/W1/EDocumentsConnector/app/src/Pagero/PageroAuth.Codeunit.al
Use procedure IsSaaSInfrastructure since for azure key vault secrets it's only important if the environment is BC SaaS or anything else.
If the key vault feature should be checked during testing then this has to be done in a BC SaaS Sandbox.
Fixes #27260
Fixes [AB#549124](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/549124)
=> Use procedure IsSaaSInfrastructure instead of IsSaaS

Build/projects/1st Party Apps (W1)/.AL-Go/NewBcContainer.ps1, Build/projects/1st Party Apps (W1)/.AL-Go/localDevEnv.settings.json
Fix localdevenv in 1st Party Apps (W1) project. Running the NewBCContainer override will unpublish all the existing 1st party apps.  If we don't we'll run into issues like: 
`Publishing failed due to 'Cannot install the extension API Reports - Finance by Microsoft 26.0.0.0 because a newer version 26.0.24098.0 was already installed.'.`
Fixes [AB#550722](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/550722)
=> Fix localdevenv in 1st Party Apps (W1) project

Apps/W1/Intrastat/app/src/IntrastatReport.Page.al
There is a problem with current implementation of "Validate Codeunit ID" and "Content Codeunit ID" in several actions on "Intrastat Report" page. I have rewritten the code so that Validate and Content codeunits can be used independently of each other. Whenever validation is performed, if "Validate Codeunit ID" is not set in "VAT Reports Configuration", standard validation code is executed. Whenever file creation is performed, if "Content Codeunit ID" is not set in "VAT Reports Configuration", standard export code is executed.
fixes #27114 
Fixes [AB#554367](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/554367)
=> [Intrastat Core] Changes to "Validate Codeunit ID" and "Content Codeunit ID" behavior on "Intrastat Report" page

Apps/W1/Intrastat/app/src/IntrastatRepCustTemCard.PageExt.al, Apps/W1/Intrastat/app/src/IntrastatReportCustTempl.TableExt.al
Based on approval:
https://github.com/microsoft/BusinessCentralApps/issues/943
This issue is generated from the following idea on [aka.ms/bcideas](https://github.com/microsoft/BusinessCentralApps/issues/aka.ms/bcideas): [Intrastat default transactions types](https://experience.dynamics.com/ideas/idea/?ideaid=ae80958c-159b-ed11-a76e-0003ff45e043)
To do the Intrastat reporting the "Default Trans. Types" must be filled on the customer card, but its not possible to add these fields to the customer template, its easy to forget to put in the data.
Please add the fields on the customer template.
Fixes #27520
Fixes [AB#461591](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/461591)
=> #943 Intrastat default transactions types

Apps/W1/HybridGP/app/src/pages/GPMigrationConfiguration.Page.al
This change enhances the migration configuration page to display a warning message if a company is configured to migrate without setting the Oldest G/L Year.
Fixes #26487
Fixes [AB#558913](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/558913)
=> GP - Config Oldest G/L Year warning message

Apps/W1/APIV2/app/src/pages/APIV2SalespersonPurchaser.Page.al, Apps/W1/APIV2/test/src/APIV2SalespersonPurchE2E.Codeunit.al
A new API page for Salespeople/Purchasers
I created the tests in a similar manner that I found suitable for Locations, but I did not manage to run the test. Thus, looking forward to the feedback if tests do pass in Microsoft Pipelines or how to test those calls in a container. Currently I do not have a clue how to do it.
Fixes #26806
Fixes [AB#541735](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/541735)
=> Salesperson API

Apps/US/HybridGP_US/app/src/Codeunits/GPCloudMigrationUS.Codeunit.al
This change corrects an issue when migrating GP Vendor 1099 data on version v25.
Changes:
- Always check to see if the new IRS Forms feature is enabled.
- Initialize the original/old IRS 1099 Forms feature if required.
Fixes #26487
Fixes [AB#560225](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/560225)
=> GP - Correct issue with IRS 1099 data migration

Apps/W1/APIV2/app/src/pages/APIV2AutExtensions.Page.al
add a new action unpublish to page ```30002 "APIV2 - Aut. Extensions"``` [link](https://github.com/microsoft/ALAppExtensions/blob/a1f39200bc76cbc45e04461000fae0675d14610f/Apps/W1/APIV2/app/src/pages/APIV2AutExtensions.Page.al).
1. User sends a request ```POST https://.../api/microsoft/automation/v2.0/companies(...)/extensions(<packageId>)/Microsoft.NAV.unpublish```
2. new unpublish action gets called
3. If package is installed, raise error
4. call ExtensionManagement.UnpublishExtension(Rec."Package ID"); to unpublish app
5. Return WebServiceActionResultCode::Deleted 
Fixes #27901
Fixes [AB#391847](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/391847)
=> Add unpublish extension action in automation api

Apps/W1/ContosoCoffeeDemoDataset/app/README.md
This PR fixes URLs for images and links in the readme for the Contoso demo tool.
Fixes [AB#573440](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/573440)
=> Fix URLs for images and links in readme for Contoso demo tool

Apps/W1/DynamicsGPHistoricalData/app/src/PageExt/CustomerListExt.PageExt.al, Apps/W1/DynamicsGPHistoricalData/app/src/PageExt/ItemListExt.PageExt.al, Apps/W1/DynamicsGPHistoricalData/app/src/PageExt/VendorListExt.PageExt.al
This update enhances the GP Historical Data page extensions to make the action labels clear and adding an 'All' version of the list pages to align with the others in this app.
Fixes [AB#575588](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/575588)
=> GP - Enhancements to the GP Historical Data page menus

Apps/W1/HybridGP/app/src/Migration/Support/HelperFunctions.codeunit.al, Apps/W1/HybridGP/app/src/codeunits/GPCloudMigration.codeunit.al
This change enhances the GP to BC migration by deleting Dimensions that are pre-installed upon company initialization, at the start of the migration.
Fixes [AB#575370](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/575370)
=> GP - Delete pre-installed Dimensions at the start of the migration

Apps/W1/SubscriptionBilling/App/Base/Codeunits/SubContractsGeneralMgt.Codeunit.al
CheckIfVendorContractExistWhenDeleteVendor and CheckIfCustomerContractOrServiceObjectExistWhenDeleteCustomer should only be used if the master data record (vendor or customer) is not temporary which is going to be deleted
Add a check to OnBeforeDeleteEvent event subscribers for both Customer and Vendor tables to bypass contract validation when records are temporary. This avoids unnecessary validation for temporary records, which do not represent persisted data and should not trigger deletion errors.
Fixes #28567 
Fixes [AB#575819](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/575819)
=> #28567 Update SubContractsGeneralMgt.Codeunit.al

Apps/W1/External File Storage - Azure File Service Connector/app/src/ExtFileShareConnectorImpl.Codeunit.al
Fixed DirectoryExists for empty directories in External File Storage - Azure File Service Connector
Fixes #28660
Fixes [AB#580052](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/580052)
=> Fixed DirectoryExists for empty directories in Azure File Service Connector

Apps/W1/SubscriptionBilling/App/Service Objects/Table Extensions/Item.TableExt.al, Apps/W1/SubscriptionBilling/App/Service Objects/Table Extensions/ItemTempl.TableExt.al
When validating the **"Subscription Option"** field, the code performs several checks. One of them is within the `UpdateItemPriceList` function, which enforces specific logic for **"Subscription Items"**:
- If the **"Subscription Option"** is set to **"Subscription Item",** the function ensures that the **"Allow Invoice Disc."** flag is **disabled** both on the Item and its related sales prices. This is because Subscription Items are excluded from document totals in Sales Quotes and Orders.
- Conversely, if the **"Subscription Option"** is _changed_ from **"Subscription Item"** to another value, the function resets **"Allow Invoice Disc."** to its default value (**true**).
This logic should execute **only when the "Subscription Option" value changes**.
However, when an Item is created …
=> Skip updating prices if "Subscription Option" has not changed

Apps/W1/SubscriptionBilling/App/Sales Service Commitments/Codeunits/SalesSubscriptionLineMgmt.Codeunit.al, Apps/W1/SubscriptionBilling/App/Sales Service Commitments/Table Extensions/SalesLine.TableExt.al, Apps/W1/SubscriptionBilling/App/Sales Service Commitments/Tables/SalesSubscriptionLine.Table.al, Apps/W1/SubscriptionBilling/Test/Service Commitments/SalesServiceCommitmentTest.Codeunit.al
In order to enable entering Subscription Items on Sales Orders and posting of the Sales Order without an error few improvements or fixes were done:
1. The function IsSalesLineWithSalesServiceCommitments has been improved in the sense that it always returns a deterministic value for a sales line regardless of the fact if the line has already been inserted and thus "Line No." generated or not. 
2. The function CalculateCalculationBaseAmount relies on up-to-date sales line record. This was so far done by (a bit hacky) call of a SalesLine.Modify on two places. Instead of modifying sales lines in the middle of processing a new function has been introduced in "Sales Subscription Line" table: SetSalesLine.
3. After fixing the code, the test TestTransferSalesServiceCommitmentsOnExplodeBOM started …
=> Subscription Item and Default Item Quantity

Apps/W1/ReviewGLEntries/app/permissions/ReviewGLEntriesRead.PermissionSet.al, Apps/W1/ReviewGLEntries/app/permissions/ReviewGLEntriesView.PermissionSet.al, Apps/W1/ReviewGLEntries/app/src/codeunits/ReviewGLEntry.Codeunit.al, Apps/W1/ReviewGLEntries/app/src/codeunits/Upgrade.Codeunit.al, Apps/W1/ReviewGLEntries/app/src/pages/ReviewGLEntries.Page.al, Apps/W1/ReviewGLEntries/app/src/pages/ReviewedGLEntries.Page.al, Apps/W1/ReviewGLEntries/app/src/tables/GLEntryReview.TableExt.al, Apps/W1/ReviewGLEntries/app/src/tables/GLEntryReviewEntry.Table.al, Apps/W1/ReviewGLEntries/app/src/tables/GLEntryReviewLog.Table.al, Apps/W1/ReviewGLEntries/test/src/ReviewGLEntriesTests.Codeunit.al
This will add the feature of remaining amount to review entries
Fixes #28318
Fixes [AB#558313](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/558313)
=> [BC Idea]: Add 'Remaining amount' field to G/L entries for partially reviewed entries

Apps/W1/Sustainability/app/src/Purchase/SustPurchaseSubscriber.Codeunit.al, Apps/W1/Sustainability/app/src/Purchase/SustainabilityPurchLine.TableExt.al
Refactor PurchaseHeader.Get(...) to `PurchaseLine.GetPurchHeader()`.
This enalbes scenarios when the Purchase Line is created before the Purchase Header is inserted.
Fixes #29107
Fixes [AB#598708](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/598708)
=> Use GetPurchHeader in Sustainability App to support Recurring Purchase Lines (Standard Purchase Code)
