README.md
Added a notification about April 19 endgame to readme file.
=> README.md April 19 endgame announcement

C52012DataMigration/src/accounts/COD1862.C5LedTableMigrator.al, C52012DataMigration/src/accounts/transactions/COD1871.C5LedTransMigrator.al, C52012DataMigration/test/COD148002.C5LedTableMigratorTest.al, C52012DataMigration/test/COD148010.C5LedTransMigratorTest.al
Migrate G/L Account Dimensions
=> Private/t neadin/migrate account dimensions

Modules/System/Satisfaction Survey/src/SatisfactionSurveyAsync.ControlAddIn.al
Fix the path to the Javascript file
=> Unable to build without this update

Modules/DevTools/TestFramework/Any/app/app.json, Modules/DevTools/TestFramework/Any/app/src/Any.Codeunit.al, Modules/DevTools/TestFramework/Assert/app/app.json, Modules/DevTools/TestFramework/Assert/app/src/LibraryAssert.Codeunit.al, Modules/DevTools/TestTools/TestRunner/app/app.json, Modules/DevTools/TestTools/TestRunner/app/src/ALTestSuite.Table.al, Modules/DevTools/TestTools/TestRunner/app/src/ALTestSuites.Page.al, Modules/DevTools/TestTools/TestRunner/app/src/ALTestTool.Page.al, Modules/DevTools/TestTools/TestRunner/app/src/CommandLineTestTool.Page.al, Modules/DevTools/TestTools/TestRunner/app/src/SelectTestRunner.Page.al, Modules/DevTools/TestTools/TestRunner/app/src/SelectTests.Page.al, Modules/DevTools/TestTools/TestRunner/app/src/SelectTestsByRange.Page.al, Modules/DevTools/TestTools/TestRunner/app/src/TestMethodLine.Table.al, Modules/DevTools/TestTools/TestRunner/app/src/TestProfileManagement.Codeunit.al, Modules/DevTools/TestTools/TestRunner/app/src/TestRoleCenter.Page.al, Modules/DevTools/TestTools/TestRunner/app/src/TestRunnerGetMethods.Codeunit.al, Modules/DevTools/TestTools/TestRunner/app/src/TestRunnerIsolCodeunit.Codeunit.al, Modules/DevTools/TestTools/TestRunner/app/src/TestRunnerIsolDisabled.Codeunit.al, Modules/DevTools/TestTools/TestRunner/app/src/TestRunnerMgt.Codeunit.al, Modules/DevTools/TestTools/TestRunner/app/src/TestRunnerProgessDialog.Codeunit.al, Modules/DevTools/TestTools/TestRunner/app/src/TestSuiteMgt.Codeunit.al
As the tests of the System Application depend on the DevTools, the DevTools need to be committed as well.
=> Initial commit of DevTools

Modules/System/Math/app.json, Modules/System/Math/src/Math.Codeunit.al
Based on https://github.com/microsoft/cal-open-library/pull/127.
=> Add Math module

BREAKINGCHANGES.md
Initial commit to set the format of error solutions.
=> Add very first error solutions.

BREAKINGCHANGES.md
Update to BREAKINGCHANGES.md with more errors and solutions.
=> Update with more breaking changes

BREAKINGCHANGES.md
Add more breaking changes with solutions.
Add section for contacting us if they are unable to find errors in the list.
=> Add more breaking changes

Modules/System/Language/README.md
Add the API documentation to Language README.
=> Update Language README with API documentation

Modules/System Test Libraries/Confirm Management/src/ConfirmTestLibrary.Codeunit.al, Modules/System/Azure AD Plan/src/AzureADPlanImpl.Codeunit.al, Modules/System/Cues and KPIs/src/CuesAndKPIsImpl.Codeunit.al, Modules/System/Extension Management/src/ExtensionManagement.Codeunit.al, Modules/System/Extension Management/src/ExtensionMarketplace.Codeunit.al, Modules/System/Headlines/src/Headlines.Codeunit.al, Modules/System/Password Dialog/src/PasswordDialogImpl.Codeunit.al, Modules/System/Recurrence Schedule/src/RecurrenceSchedule.Codeunit.al, Modules/System/Satisfaction Survey/src/SatisfactionSurveyImpl.Codeunit.al
=> Typing error

BREAKINGCHANGES.md
Assisted Setup module has recently been added to 15.x and breaks existing code. A section has been added to hep users migrate while using the new module.
=> Adding Assisted Setup compiling scenarios

BREAKINGCHANGES.md
Update Breaking Changes doc with Data Compression issues
=> Update Breaking Changes doc

Modules/System/Translation/README.md
Add `README.md` file. Content from [Translation Module in Dynamics 365 Business Central](https://cloudblogs.microsoft.com/dynamics365/it/2019/09/20/translation-module-in-dynamics-365-business-central/) (Author: [Soumyadutta](https://cloudblogs.microsoft.com/dynamics365/author/soumyadutta/))
=> Add README.md file for Translation Module

Modules/System/Cryptography Management/src/RijnadaelManagementTest.Codeunit.al, Modules/System/Cryptography Management/src/RijndaelManagement.Codeunit.al, Modules/System/Cryptography Management/src/RijndaelManagementImpl.Codeunit.al, Modules/System/Cryptography Management/src/dotnet.al
Required by my Integration App that is integrating with a PHP web site.  Intention to put that App onto AppSource for release 15.
=> Add Code and Test Code

Modules/System Tests/BLOB Storage/src/TempBlobTest.Codeunit.al, Modules/System/BLOB Storage/src/TempBlob.Codeunit.al, Modules/System/BLOB Storage/src/TempBlobImpl.Codeunit.al
=> BLOB Storage Module Extended by From an To FieldRef

BREAKINGCHANGES.md
Hi,
I mentioned on Yammer before that there were some more Breaking Changes in the BaseApp and System App. Since they are still not on the list I'm writing this PR. On my original Yammer question are still changes that puzzle me. I'm adding the ones I have a reasonable solution to here.
https://www.yammer.com/dynamicsnavdev/threads/360466591072256
Cheers Leon
=> Adding to breaking changes

Modules/System/Language/src/Language.Codeunit.al, Modules/System/Language/src/LanguageImpl.Codeunit.al
Added a function to get Parent Language ID from Windows Culture Info
=> Add Parent Language ID

Modules/System Tests/Cryptography Management/src/Rfc2898DeriveBytesTest.Codeunit.al, Modules/System/Cryptography Management/src/CryptographyManagementImpl.Codeunit.al, Modules/System/Cryptography Management/src/Rfc2898DeriveBytes.Codeunit.al, Modules/System/Cryptography Management/src/dotnet.al
As per ticket https://github.com/microsoft/ALAppExtensions/issues/2043 hereby the suggested code
=> Rfc2898derivebytes codeunit

BREAKINGCHANGES.md
MakeText, MakeDateText, MakeTimeText and MakeDateTimeText were removed.
=> Update BREAKINGCHANGES.md - TextManagement changes

BREAKINGCHANGES.md
Update BREAKINGCHANGES.md to fix TextEndsWith solution and provide an example.
=> Update BREAKINGCHANGES.md to fix TextEndsWith solution

Modules/System Tests/XmlWriter/app.json, Modules/System Tests/XmlWriter/src/XmlWriterTest.Codeunit.al, Modules/System/XmlWriter/README.md, Modules/System/XmlWriter/app.json, Modules/System/XmlWriter/src/XmlWriter.Codeunit.al, Modules/System/XmlWriter/src/XmlWriterImpl.Codeunit.al, Modules/System/XmlWriter/src/dotnet.al
Hi Microsoft team,
Can you please review this Pull Request? Hopefully this will be the last one :)
=> Xml Writer

Modules/System/Azure AD Licensing/README.md, Modules/System/Azure AD User/README.md, Modules/System/Base64 Convert/README.md, Modules/System/Cryptography Management/README.md, Modules/System/Email/README.md, Modules/System/Email/src/Account/EmailAccount.Codeunit.al, Modules/System/Email/src/Connector/EmailConnector.Interface.al, Modules/System/Email/src/Email/Email.Codeunit.al, Modules/System/Email/src/Email/EmailActivities.Page.al, Modules/System/Email/src/Email/Outbox/EmailAction.Enum.al, Modules/System/Email/src/Message/EmailMessage.Codeunit.al, Modules/System/Email/src/Scenario/EmailScenario.Codeunit.al, Modules/System/Email/src/Test Email/EmailTestMail.Codeunit.al, Modules/System/Email/src/Test Email/EmailUserSpecifiedAddress.Page.al, Modules/System/Environment Information/README.md, Modules/System/Extension Management/README.md, Modules/System/Feature Key/README.md, Modules/System/Geolocation/README.md, Modules/System/OAuth2/README.md, Modules/System/Page Summary Provider/README.md, Modules/System/Retention Policy/README.md, Modules/System/Sandbox Cleanup/README.md, Modules/System/Secrets/README.md, Modules/System/Server Settings/README.md, Modules/System/SmartList Designer Subscribers/README.md, Modules/System/Translation/README.md, Modules/System/URI/README.md, Modules/System/XmlWriter/README.md
Regenerated all documentation.
=> Update documentation for all modules.

Modules/System Tests/XmlWriter/src/XmlWriterTest.Codeunit.al, Modules/System/XmlWriter/src/XmlWriter.Codeunit.al, Modules/System/XmlWriter/src/XmlWriterImpl.Codeunit.al
Hi Microsoft team,
Can you please add these two new functions for Xml Writer, for both BC16 and BC17?
=> Added two additonal functions for Xml Writer

Modules/System Tests/Cryptography Management/src/RijndaelCryptographyTest.Codeunit.al, Modules/System/Cryptography Management/README.md, Modules/System/Cryptography Management/src/RijndaelCryptography.Codeunit.al
Just a couple of typos that jumped out at me
=> Fix typos 

Modules/System/Extension Management/src/ExtensionManagement.Codeunit.al, Modules/System/Extension Management/src/ExtensionOperationImpl.Codeunit.al
New procedure in the Extension Management codeunit to enable access to extension source code from al
procedure GetExtensionSource(PackageId: Guid; var TempBlob: Codeunit "Temp Blob"; var CleanFileName: Text): Boolean
=> Added GetExtensionSource

Modules/DevTools/BusinessCentralPerformanceToolkit/src/BCPTLine.Codeunit.al
Added Dimensions for "Version" and "BCPT Line No" to Procedure "AddLogAppInsights" in COD 149005 "BCPTLine.Codeunit" to allow detailed analysis of telemetry
=> Add Version and Line No. to BCPT Telemetry

Modules/DevTools/BusinessCentralPerformanceToolkit.code-workspace
References to the original ApplicationBenchmarkTool should be updated to BusinessCentralPerformanceToolkit
=> Update multiroot workspace file BusinessCentralPerformanceToolkit

Modules/DevTools/BusinessCentralPerformanceToolkit/src/BCPTLine.Table.al, Modules/DevTools/BusinessCentralPerformanceToolkit/src/BCPTLines.Page.al, Modules/DevTools/BusinessCentralPerformanceToolkit/src/BCPTSetupCard.Page.al, Modules/DevTools/BusinessCentralPerformanceToolkit/src/BCPTSetupList.Page.al
Fixed "with" issues, "overflow" warning and "Default Delay Times"
=> Fixed "with" issues, "overflow" warning and "Default Delay Times"

Modules/System/Email/src/Email/Email.Codeunit.al, Modules/System/Email/src/Email/EmailImpl.Codeunit.al
#12537
- Added OnAfterValidateEmailMessage publisher
- Moved all emailMessage validations into separate ValidateEmailMessage function.
- Raised OnAfterValidateEmailMessage publisher
=> Add OnAfterValidateEmailMessage to allow performing tests before sending mail

Modules/System Tests/Email/src/EmailTest.Codeunit.al, Modules/System/Email/src/Email/Email.Codeunit.al, Modules/System/Email/src/Email/EmailImpl.Codeunit.al
issue 13699
two new procedures and related tests were added:
GetOutboxEmailsForRecord - gets Outbox Emails for Source Record
GetOutboxEmailRecordStatus - gets Email Status of record in Outbox Emails table
=> GetOutboxEmailsForRec., GetOutboxEmailRecordStatus

.github/workflows/test.yml, intrigus-lgtm.txt
=> Action test

Apps/DK/OIOUBL/app/src/SalesCreditMemo/ExportSalesCrMemo.Codeunit.al, Apps/DK/OIOUBL/app/src/SalesInvoice/ExportSalesInvoice.Codeunit.al, Apps/DK/OIOUBL/app/src/ServiceCreditMemo/ExportServiceCrMemo.Codeunit.al, Apps/DK/OIOUBL/app/src/ServiceInvoice/ExportServiceInvoice.Codeunit.al, Apps/DK/OIOUBL/test/src/ERMElecDocumentSales.Codeunit.al, Apps/DK/OIOUBL/test/src/ERMMiscElecInvoice.Codeunit.al, Apps/DK/OIOUBL/test/src/ElecServiceDocument.Codeunit.al
=> Use Amount-Rounding in PriceAmount element

Modules/System Tests/Image/src/ImageTests.Codeunit.al, Modules/System/Image/src/Image.Codeunit.al, Modules/System/Image/src/ImageImpl.Codeunit.al, Modules/System/Image/src/RotateFlipType.Enum.al
Added new procedures for rotating/flipping and clearing an image.
=> Added Image capabilities

Modules/System/Azure Storage Services Authorization/src/SharedKey/StorServAuthSharedKey.Codeunit.al
=> #15409: Lock 'SignaturePlaceHolderLbl' to avoid translation

Modules/System Tests/Cryptography Management/src/RSACryptoServiceProviderTests.Codeunit.al, Modules/System/Cryptography Management/src/X509Certificate2.Codeunit.al, Modules/System/Cryptography Management/src/X509Certificate2Impl.Codeunit.al
Changes are in 20.x but not 20.2. Out of band update but for partner to view changes that are coming.
=> Update Cryptography Management

Apps/W1/DynamicsGPHistorySmartLists/app/src/Queries/Que3005.GP_HistReceivablesTransactions.al, Apps/W1/DynamicsGPHistorySmartLists/app/src/Queries/Que3006.GP_OpenReceivablesTransactions.al, Apps/W1/DynamicsGPHistorySmartLists/app/src/Queries/Que3008.GP_HistPayablesTransactions.al
Added additional fields to the following queries:
- 3005, GPHistReceivablesTrx
- 3006, GPOpenReceivablesTrx
- 3008, GPHistPayablesTrx
=> Added more fields to SmartList queries.

Modules/System/Email/src/Email/Email.Codeunit.al
Improve obsoletion code doc for event OnAfterSendEmail in Email codeunit.
Fixes #18407
=> Improve obsoletion doc for event OnAfterSendEmail

Modules/System/Extension Management/src/ExtensionManagement.Codeunit.al
There was no SaaS access to the detailed deployment message from the Extension Management codeunit. Functions exposed.
/Erik
=> Access to deployment detailed message

Apps/W1/HybridGP/app/src/Migration/Support/CheckBooks/GPCheckbookMigrator.codeunit.al
Moving the GP Last Reconciled Balance amount from Bank account's "Balance Last Statement" to proper general journal entry.
=> GP to BC migration Last Reconciled Balance

Modules/System/Cryptography Management/src/SymmetricAlgorithm.Interface.al
Fix warning in SymmetricAlgorithm interface - TechDays 2022
=> Fix warning in SymmetricAlgorithm interface

.github/workflows/AddExistingAppOrTestApp.yaml, .github/workflows/CICD.yaml, .github/workflows/CreateApp.yaml, .github/workflows/CreateOnlineDevelopmentEnvironment.yaml, .github/workflows/CreatePerformanceTestApp.yaml, .github/workflows/CreateTestApp.yaml, .github/workflows/Current.yaml
=> Change runs-on to "self-hosted", "1ES.Pool=ALAppExtensions"

.github/RELEASENOTES.copy.md, .github/workflows/CICD.yaml, .github/workflows/CreateApp.yaml, .github/workflows/CreateOnlineDevelopmentEnvironment.yaml, .github/workflows/CreatePerformanceTestApp.yaml, .github/workflows/CreateRelease.yaml, .github/workflows/CreateTestApp.yaml, .github/workflows/IncrementVersionNumber.yaml, .github/workflows/NextMajor.yaml, .github/workflows/NextMinor.yaml, .github/workflows/PublishToEnvironment.yaml, .github/workflows/UpdateGitHubGoSystemFiles.yaml, Modules/.AL-Go/cloudDevEnv.ps1, Modules/.AL-Go/localDevEnv.ps1
Note that when using the preview version of AL-Go for GitHub, you need to Update your AL-Go system files, as soon as possible when told to do so.
- Issue #143 Commit Message for **Increment Version Number** workflow
- Issue #160 Create local DevEnv aith appDependencyProbingPaths
- Issue #156 Versioningstrategy 2 doesn't use 24h format
- Issue #155 Initial Add existing app fails with "Cannot find path"
- Issue #152 Error when loading dependencies from releases
- Issue #168 Regression in preview fixed
- Issue #189 Warnings: Resource not accessible by integration
- Issue #190 PublishToEnvironment is not working with AL-Go-PTE@preview
- Issue #186 AL-GO build fails for multi-project repository when there's nothing to build
- When you have GitHub pages enabled, AL-Go for GitHub would try to …
=> 'Updated AL-Go System Files'

Modules/System Tests/Translation/src/TranslationTests.Codeunit.al
Add missing test cases in the Translation module.
=> Add missing tests in Translation module

Modules/DevTools/TestFramework/TestLibraries/Any/src/Any.Codeunit.al
Hi,
very often, when I write tests, I need a method that will return a random boolean and I don't know why, but so far such a method is not in Any library and I always had to write its on the side. 
So I decided to add it
=> Add pseudo-random boolean method

Modules/System/SharePoint Authorization/src/AuthorizationCode/SharePointAuthorizationCode.Codeunit.al
This PR fixes the parameter assignment of the tenant id.
=> Fix Sharepoint Authorization

Modules/System/SharePoint Authorization/src/AuthorizationCode/SharePointAuthorizationCode.Codeunit.al
=> Add missing semicolon;

.github/workflows/CICD.yaml, .github/workflows/Current.yaml, .github/workflows/NextMajor.yaml, .github/workflows/NextMinor.yaml, .github/workflows/PullRequestHandler.yaml
=> Updated AL-Go System Files

.github/workflows/CICD.yaml, Modules/.AL-Go/CompileAppInBcContainer.ps1
Build apps with translation files
=> Build apps with translation files

.github/ALAppExtensions.template.nuspec, .github/DeliverToBCFeed.ps1
Referencing: https://learn.microsoft.com/en-us/nuget/reference/nuspec#license
=> Place the license file in the nuget package

CODEOWNERS, Modules/DevTools/BusinessCentralPerformanceToolkit/src/BCPTHeader.Codeunit.al, Modules/DevTools/BusinessCentralPerformanceToolkit/src/BCPTHeader.Table.al, Modules/DevTools/BusinessCentralPerformanceToolkit/src/BCPTLine.Codeunit.al, Modules/DevTools/BusinessCentralPerformanceToolkit/src/BCPTLine.Table.al, Modules/DevTools/BusinessCentralPerformanceToolkit/src/BCPTLogEntries.Page.al, Modules/DevTools/BusinessCentralPerformanceToolkit/src/BCPTLogEntry.Table.al, Modules/DevTools/BusinessCentralPerformanceToolkit/src/BCPTStartTests.Codeunit.al, Modules/System Test Libraries/Retention Policy/src/RetenPolTestInstaller.Codeunit.al, Modules/System Tests/Retention Policy/src/RetenPolAllowedTblTest.Codeunit.al, Modules/System/Email/src/EmailInstaller.Codeunit.al, Modules/System/Retention Policy/src/Install/RetentionPolicyInstaller.Codeunit.al, Modules/System/Retention Policy/src/Retention Policy Allowed Tables/RetenPolAllowedTables.Codeunit.al, Modules/System/Retention Policy/src/Retention Policy Setup/RetentionPolicySetupCard.Page.al
- Add refresh allowed table policies action and fix company initialize issue
- No way to correlate BCPT runs and run lines
=> Uptake latest changes to Modules

Modules/System/Azure Storage Services Authorization/src/SAS/SASParameters.Table.al, Modules/System/Azure Storage Services Authorization/src/SAS/StorServAuthSAS.Codeunit.al, Modules/System/Azure Storage Services Authorization/src/StorServAuthImpl.Codeunit.al, Modules/System/Azure Storage Services Authorization/src/StorageServiceAPIVersion.Enum.al
Api Version: https://learn.microsoft.com/de-de/rest/api/storageservices/version-2020-12-06
=> Enable support to specify the optional Signed Encryption Scope (ses) for API Version 2020-12-06

CODEOWNERS
Use team rather than individuals as default code reviewers.
=> Use team rather than individuals

Modules/System/Permission Sets/src/PermissionSetRelation.Codeunit.al, Modules/System/Permission Sets/src/PermissionSetRelationImpl.Codeunit.al
Fixes https://github.com/microsoft/ALAppExtensions/issues/21197
=> Added new procedure "Permission Set Relation".AddNewPermissionSetRelation

Apps/W1/HybridGP/app/src/Migration/GPTables/GPGL00100.Table.al, Apps/W1/HybridGP/app/src/Migration/GPTables/GPGL10110.Table.al, Apps/W1/HybridGP/app/src/Migration/GPTables/GPGL10111.Table.al
Fix a merge issue I found this morning. The merge yesterday made 3 of the table files empty.
=> Fix merge issue

Modules/System/Guided Experience/src/Guided Experience/GuidedExperience.Codeunit.al
There were already two methods for translating the Title and Description, but not for Short Title!
=> [Guided Experience] Add Translation For Setup Object Short Title

Build/Scripts/PackNuget.ps1
Update package name from microsoft-ALAppExtensions-Modules-preview to microsoft.ALAppExtensions.Modules
=> Update package name

.github/workflows/PublishNuget.yaml
Move Nuget Token to new secret
=> Move Nuget Token to new secret

.github/workflows/CICD.yaml, Build/Scripts/CreateAppPackageOutput.ps1
Remove BuildArtifacts folder in buildoutput
=> Remove BuildArtifacts folder in buildoutput 

Modules/System Tests/Record Link Management/src/RecordLinkMgtTest.Codeunit.al
As discussed in this PR https://github.com/microsoft/BusinessCentralApps/pull/180, adding a test to cover copying of multiple record links. @pri-kise
=> Test copying multiple record links

Build/Scripts/UpdateBaselineVersion.ps1
Auto merge baseline version PRs
=> Auto merge baseline version PRs

Test Framework/.AL-Go/settings.json
Build translated Test Framework (See BuildApplicationLanguagePacks.ps1)
=> Build translated Test Framework

Apps/W1/ConnectivityApps/app/src/Codeunits/ConnectivityAppDefinitions.Codeunit.al
=> Adding Softera.Bankfeed to Connectivity Apps

Other/Tests/BCPT-SampleTests/src/BCPTAdjustCostItemEntries.Codeunit.al, Other/Tests/BCPT-SampleTests/src/BCPTCalculatePlanWorksheet.Codeunit.al
1. Adjust cost of item ledger entries
2. Calculate plan worksheet
@henrikfrovst
=> Added two BCPT scenarios:

Modules/System/Azure Storage Services Authorization/src/StorageServiceAPIVersion.Enum.al
Add more values to Storage Service API Version enum.
=> Add new storage service API versions

Other/Tests/BCPT-SampleTests/src/BCPTCPostPurchInv.Codeunit.al, Other/Tests/BCPT-SampleTests/src/BCPTPostGLEntries.Codeunit.al, Other/Tests/BCPT-SampleTests/src/BCPTPostPurchInv.Codeunit.al, Other/Tests/BCPT-SampleTests/src/TestCodeunitsWithParams.Enum.al
Added two scenarios for BCPT:
- Posting Purchase Invoice
- Posting General Journal
@henrikfrovst
=> Two new scenarios for GL entries and

Apps/W1/AuditFileExport/app/src/ExportEngine/AuditFileExportMgt.Codeunit.al, Modules/System/Azure Storage Services Authorization/src/SAS/StorServAuthSAS.Codeunit.al, Modules/System/Azure Storage Services Authorization/src/SharedKey/StorServAuthSharedKey.Codeunit.al
Fixes #23805
This PR locks labels that should never be translated.
=> Lock Labels for Storage Service Authorization

System Application Modules/.AL-Go/settings.json
- Build the tests
- Do not run the tests
=> Change AL-GO settings for System Application modules

Modules/System/Extension Management/src/ExtensionSettings.Page.al
Remove Group Caption since the Caption wasn't translated and it didn't provide any value.
=> Enhance UI of extension settings

Modules/System Tests/Retention Policy/src/RetentionPeriodTest.Codeunit.al, Modules/System/Retention Policy/src/Retention Period/RetentionPeriodEnum.Enum.al, Modules/System/Retention Policy/src/Retention Period/RetentionPeriodImpl.Codeunit.al
Add New Retention period for 3 Years:
This is very common for our customers on some tables in germany.
- Added Test Case for 28 Days Retention Period.
- Unified the tests for the retentio period
=> Add Retention Period for 3 Years

Modules/System Tests/URI/src/UriTest.Codeunit.al, Modules/System/URI/src/Uri.Codeunit.al, Modules/System/URI/src/UriKind.Enum.al
Add methods:
- IsWellFormedUriString
- IsBaseOf
to URI Codeunit.
Updated tests to work independent by making the global variable URI local.
=> Improve URI with more Wrappers

Modules/System Test Libraries/Translation/src/TranslationTestTable.Table.al, Modules/System Tests/Translation/app.json, Modules/System Tests/Translation/src/TranslationTests.Codeunit.al, Modules/System/Translation/src/Translation.Codeunit.al, Modules/System/Translation/src/Translation.Page.al, Modules/System/Translation/src/TranslationImplementation.Codeunit.al
Fixes  [#12381](https://github.com/microsoft/ALAppExtensions/issues/12381)
Currently the length check is optional an only performed via UI
=> Check for Field Length on setting via UI

Modules/System/Telemetry/src/Logging/Telemetry.Codeunit.al
Add Example for an Implementation of the Telemetry Logger Interface to the Telemetry Logger Codeunit
=> [Documentation] Add example code for Telemetry Logger

Modules/System Tests/Azure Blob Services API/src/ABSBlobClientTest.Codeunit.al, Modules/System/Azure Blob Services API/src/ABSBlobClient.Codeunit.al, Modules/System/Azure Blob Services API/src/ABSClientImpl.Codeunit.al, Modules/System/Azure Blob Services API/src/ABSOperationResponse.Codeunit.al, Modules/System/Azure Blob Services API/src/Helper/ABSOptionalParameters.Codeunit.al, Modules/System/Azure Blob Services API/src/Helper/ABSWebRequestHelper.Codeunit.al
Some improvements to the Azure Blob Storage module:
New functions:
* GetBlobProperties
* BlobExists
Remark: BlobExists uses GetBlobProperties, similar to the C# code of Azure SDK.
Improvement on CopyBlob to support blobs from the same storage account.
=> Azure Blob Storage improvements

Apps/W1/ServiceDeclaration/app/src/Processing/ServiceDeclarationMgt.Codeunit.al
=> Refactor Service Declaration Mgt for temporary SalesHeader/PurchHeader

.github/AL-Go-Settings.json
"UpdateALGoSystemFilesEnvironment" setting is needed to specify the environment where to run "Update AL-Go System Files"
=> Add to "UpdateALGoSystemFilesEnvironment" to AL-Go-Settings.json

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/WorkitemValidation.yaml
Updates to workitem validation and add PR template
Fixes [AB#494845](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/494845)
=> Updates to workitem validation

Apps/W1/AuditFileExport/app/src/GLAccountMapping/StandardAccount.Table.al, Apps/W1/AuditFileExport/app/src/GLAccountMapping/StandardAccountCategory.Table.al, Apps/W1/AuditFileExport/app/src/GLAccountMapping/StandardAccounts.Page.al
Fixes table relation property, because the first pk field is Type(Enum)
Added not blank property to primary key fields
Change control order on page like as primary key order
Fixes #25251
Fixes [AB#502390](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/502390)
=> [Bug]: Is not posible to create a G/L Account Mapping using Client

Apps/CZ/CashDeskLocalization/app/Src/Tables/CashDeskRepSelectionsCZP.Table.al, Apps/CZ/CompensationLocalization/app/Src/Tables/CompensReportSelectionsCZC.Table.al
Fix wrong table relation form AllObject to AllObjectWithCaption in Table 11748 "Cash Desk Rep. Selections CZP" and Table 31271 "Compens. Report Selections CZC"
Fixes #26007
Fixes [AB#506440](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/506440)
Fixes [AB#506440](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/506440)
=> [Bug]: Failing Page 31169 "Report Selection Cash Desk CZP"

Apps/W1/Sustainability/app/src/Journal/SustainabilityJnlLine.Table.al
This PR adds similiar methods and events as already available in other Journal Line Tables
Fixes #26273
Fixes [AB#525140](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/525140)
=> Sustainability Journal  Line - Extensibility for Default Dimensions

CODEOWNERS
Fixes [AB#420000](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/420000)
=> Update CODEOWNERS with EDocument reviewers

.github/AL-Go-Settings.json, .github/workflows/CICD.yaml, .github/workflows/DeployReferenceDocumentation.yaml, .github/workflows/PullPowerPlatformChanges.yaml, .github/workflows/PullRequestHandler.yaml, .github/workflows/PushPowerPlatformChanges.yaml, .github/workflows/Troubleshooting.yaml, .github/workflows/UpdateGitHubGoSystemFiles.yaml, .github/workflows/_BuildALGoProject.yaml, .github/workflows/_BuildPowerPlatformSolution.yaml, Build/projects/1st Party Apps (W1)/.AL-Go/cloudDevEnv.ps1, Build/projects/1st Party Apps (W1)/.AL-Go/localDevEnv.ps1, Build/projects/1st Party Apps Tests (W1)/.AL-Go/cloudDevEnv.ps1, Build/projects/1st Party Apps Tests (W1)/.AL-Go/localDevEnv.ps1
Fixes [AB#420000](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/420000)
=> Update AL-Go System Files

Apps/W1/ServiceDeclaration/app/src/ServiceDocuments/ServDeclServLine.TableExt.al
Use correct Header
Fixes #27462 
Fixes [AB#555792](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555792)
=> Service Declaration - Service Line Use Correct Header

Apps/W1/ServiceDeclaration/app/src/PurchaseDocuments/ServDeclPurchLine.TableExt.al, Apps/W1/ServiceDeclaration/app/src/SalesDocuments/ServDeclSalesLine.TableExt.al
Use GetSalesHeader and GetPurchHeader.
See also: https://www.yammer.com/dynamicsnavdev/threads/3023362906750976
Fixes #25222 
Fixes [AB#555560](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555560)
=> Service Declaration Bugfix for Temp Sales / Purchase Lines

Apps/W1/EDocument/app/src/Service/ServiceParticipant.Table.al
Fixes [AB#555357](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555357)
=> Add missing

CODEOWNERS
Update CODEOWNERS for EDocuments
Fixes [AB#556370](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/556370)
=> Update CODEOWNERS for EDocuments

.github/ISSUE_TEMPLATE/bcidea.yaml, .github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/extensibility-request.yaml
Uptake issue types
Fixes [AB#555781](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555781)
=> Uptake issue types

Apps/W1/External File Storage - SharePoint Connector/app/src/ExtSharePointConnectorImpl.Codeunit.al
Fixes procedure DirectoryExists for the Externa File Storage SharePoint Connector
Fixes #28070
Fixes [AB#565022](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/565022)
=> External File Storage: Fix DirectoryExists for SharePoint Connector

.github/workflows/ProcessPRLabel.yaml
Add comments to PRs based on labels
Fixes [AB#567078](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/567078)
=> Add comments to PRs based on labels

Apps/W1/AuditFileExport/app/src/GLAccountMapping/StandardAccounts.Page.al
Added field Type to Standard Accounts page and make the Category No. visible.
Fixes #27438
Fixes [AB#568315](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/568315)
=> Add The Type field on page "Standard Accounts"

Apps/W1/Email - Outlook REST API/app/src/EmailOutlookAPISetup.Page.al
Added ApplicationArea to Outlook API Setup page
Fixes #28330
Fixes [AB#569002](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/569002)
=> Insert ApplicationArea to Outlook API Setup page

Apps/W1/External File Storage - Azure File Service Connector/app/src/ExtFileShareConnectorImpl.Codeunit.al
- Fixed Bug that soruce and target were swapped
- Support for non ANSI Characters
Fixes #28349
Fixes [AB#572355](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/572355)
=> Fix CopyFile in Ext. File Share Connector Impl

Apps/CH/SwissQRBill/app/src/IncomingDocuments/SwissQRBillIncomingDoc.Codeunit.al, Apps/CH/SwissQRBill/app/src/purchases/SwissQRBillPurchases.Codeunit.al
The event allows to import Automatic Import the QRBill document from other Systems and Handle Decoding and Rest by the Standart Code.
Fixes #28131
[AB#565793](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/565793)
=> New Event OnQRBillImportDecodeBeforeQRBillImport for Override the QRScan Process

.github/ISSUE_TEMPLATE/extensibility-request.yaml
Update as per review comments.
Fixes [AB#573192](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/573192)
=> Update the extensibility-request issue template

.github/ISSUE_TEMPLATE/extensibility-request.yaml
Update issue form for extensibility requests
Fixes [AB#565060](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/565060)
=> Update issue form

Apps/W1/AuditFileExport/app/src/AuditFileExportFormat.Enum.al, Apps/W1/AuditFileExport/app/src/CheckAuditData/AuditDataCheckStatus.Enum.al, Apps/W1/AuditFileExport/app/src/ExportEngine/AuditFileExportDataClass.Enum.al, Apps/W1/AuditFileExport/app/src/GLAccountMapping/CopyGLAccountMapping.Report.al, Apps/W1/AuditFileExport/app/src/GLAccountMapping/GLAccMappingPeriodType.Enum.al, Apps/W1/AuditFileExport/app/src/GLAccountMapping/StandardAccountType.Enum.al, Apps/W1/AuditFileExport/app/src/Permissions/AuditExportEdit.PermissionSet.al, Apps/W1/AuditFileExport/app/src/Permissions/AuditExportRead.PermissionSet.al, Apps/W1/AuditFileExport/app/src/Setup/AuditFileExportSetup.Page.al, Apps/W1/SAF-T/app/src/CheckAuditDataSAFT/MissingFieldSAFT.Table.al, Apps/W1/SAF-T/app/src/ExportEngineSAFT/AuditFileExportHeaderSAFT.TableExt.al, Apps/W1/SAF-T/app/src/MasterDataMapping/DimensionSAFT.TableExt.al, Apps/W1/SAF-T/app/src/MasterDataMapping/SourceCodeSAFT.Table.al, Apps/W1/SAF-T/app/src/MasterDataMapping/VATPostingSetupSAFT.TableExt.al, Apps/W1/SAF-T/app/src/Permissions/SAFTEdit.PermissionSet.al, Apps/W1/SAF-T/app/src/Permissions/SAFTRead.PermissionSet.al, Apps/W1/SAF-T/app/src/SAFTModification.Enum.al, Apps/W1/SAF-T/app/src/Setup/AuditExportDataTypeSAFT.EnumExt.al, Apps/W1/SAF-T/app/src/Setup/AuditFileExportSetupSAFT.TableExt.al, Apps/W1/SAF-T/app/src/Setup/CompanyContactSAFT.TableExt.al, Apps/W1/SAF-T/app/src/Setup/SAFTWizard.Page.al
Added missing captions for Audit File Export and SAF-T extension. Empty captions add locked, or for some groups added show caption false.
Fixes #28474
Fixes [AB#573842](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/573842)
=> [SAFT] Add missing captions

Apps/W1/AuditFileExport/app/src/ExportEngine/AuditFileExportMgt.Codeunit.al
Remove the loop by export documents when restart task
Fixes #28339 
Fixes [AB#573841](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/573841)
=> Audit File Export. Remove the loop by export documents when restart task

.github/workflows/ProcessPRLabel.yaml
Add comment when issues are approved
Fixes [AB#575623](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/575623)
=> Add comment when issues are approved

Apps/W1/HybridSL/app/app.json, Apps/W1/HybridSL/app/src/Migration/Accounts/SLAccountMigrator.Codeunit.al, Apps/W1/HybridSL/app/src/Migration/Customers/SLCustomerMigrator.Codeunit.al, Apps/W1/HybridSL/app/src/Migration/SLTables/SLPopulateAccountHistory.Codeunit.al, Apps/W1/HybridSL/app/src/Migration/SLTables/SLPopulateFiscalPeriods.Codeunit.al, Apps/W1/HybridSL/app/src/codeunits/SLFiscalPeriods.Codeunit.al
Updated codeunit 47004 "SL Fiscal Periods" and codeunit 47003 "SL Populate Fiscal Periods" to support a 13th fiscal period. This resolves the accounting period already exists error.
Fixes [AB#574415](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/574415)
=> Hybrid SL - Bug 574415 - The Record in table Accounting Period already exists

.github/AL-Go-Settings.json, .github/RELEASENOTES.copy.md, .github/workflows/CICD.yaml, .github/workflows/DeployReferenceDocumentation.yaml, .github/workflows/PullRequestHandler.yaml, .github/workflows/Troubleshooting.yaml, .github/workflows/UpdateGitHubGoSystemFiles.yaml, .github/workflows/_BuildALGoProject.yaml, Build/projects/1st Party Apps (W1)/.AL-Go/cloudDevEnv.ps1, Build/projects/1st Party Apps (W1)/.AL-Go/localDevEnv.ps1, Build/projects/1st Party Apps Tests (W1)/.AL-Go/cloudDevEnv.ps1, Build/projects/1st Party Apps Tests (W1)/.AL-Go/localDevEnv.ps1
Update AL-Go System Files
Fixes [AB#539394](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/539394)
=> [main] Update AL-Go System Files

Apps/W1/HybridSL/app/src/Migration/Customers/SLCustClass.Table.al, Apps/W1/HybridSL/app/src/Migration/Customers/SLCustomerMigrator.Codeunit.al, Apps/W1/HybridSL/app/src/Migration/Support/SLHelperFunctions.Codeunit.al, Apps/W1/HybridSL/app/src/Permissions/SLD365BASICISVMSL.PermissionSetExt.al, Apps/W1/HybridSL/app/src/Permissions/SLD365BASICMSL.PermissionSetExt.al, Apps/W1/HybridSL/app/src/Permissions/SLD365TEAMMEMBERMSL.PermissionSetExt.al, Apps/W1/HybridSL/app/src/Permissions/SLINTELLIGENTCLOUDMSL.PermissionSetExt.al, Apps/W1/HybridSL/app/src/Permissions/SLMigrationEdit.PermissionSet.al, Apps/W1/HybridSL/app/src/Permissions/SLMigrationObjects.PermissionSet.al, Apps/W1/HybridSL/app/src/Permissions/SLMigrationRead.PermissionSet.al, Apps/W1/HybridSL/app/src/codeunits/SLCloudMigration.Codeunit.al, Apps/W1/HybridSL/app/src/codeunits/SLHybridWizard.Codeunit.al, Apps/W1/HybridSL/app/src/pages/SLCompanyAddSettingsList.Page.al, Apps/W1/HybridSL/app/src/pages/SLMigrationConfiguration.Page.al
Update to include migration of Dynamics SL Customer Classes to Business Central Customer Posting Groups
Fixes [AB#567568](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/567568)
=> SL Customer Class Migration Update

Apps/W1/SubscriptionBilling/App/Billing/Codeunits/SalesDocuments.Codeunit.al
implements a better isHandled pattern
Fixes #28803 
Fixes [AB#582434](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/582434)
=> #28803 fixed better isHandled pattern f.

Apps/DE/EDocumentDE/app/src/ZUGFeRD/ImportZUGFeRDDocument.Codeunit.al
- Lock Labels
- Make message to an error
Fixes #28845 
Fixes [AB#591375](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/591375)
=> Improve ZUGFeRD Code

Apps/W1/ConnectivityApps/app/src/Codeunits/ConnectivityAppDefinitions.Codeunit.al
Add DE to Yavrio Open Banking in ConnectivityAppDefinitions.Codeunit.al
Fixes [AB#596227](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/596227)
=> Update Yavrio in ConnectivityAppDefinitions.Codeunit.al
